### ISSUE TITLE
Sort by Top

### ISSUE THREAD

**Issue by TheSaneWriter** [hjiangsu/thunder#101]
**Is your feature request related to a problem? Please describe.**
Right now, the Thunder app has all of the native Lemmy sorts except for the ability to sort by Top. That's my favorite sort method, so I would really like for that to be added.

**Describe the solution you'd like**
When I click the select sort button, one of the options is sort by Top, and then when tap it it has time-frames available (usually day, month, and all time).

**Describe alternatives you've considered**
Same as above, except with 3 separate buttons, one for each timeframe.

**Comment by JulianPaulus** [comment]
I tried designing this:
![Screenshot_1687802522](https://github.com/hjiangsu/thunder/assets/6230679/675ecf51-6983-4fa0-aba5-ab0e14d4299e)

![Screenshot_1687802526](https://github.com/hjiangsu/thunder/assets/6230679/2530f76f-6a64-442d-a06c-dd4237bf0e06)

I'm mostly having problems finding the right Icons :)
@hjiangsu I also think this could be combined with the redesign of the sort picker in the settings.

**Comment by hjiangsu** [comment]
@JulianPaulus oh man, that looks pretty good to me! Same here, I have a hard time trying to find the proper icons 😅

**Comment by CTalvio** [comment]
Maybe a clock with the hour hand in different spots for the hourly top times?

**Comment by hjiangsu** [comment]
This has been added thanks to @JulianPaulus and will be available in the next release!

**Comment by hjiangsu** [comment]
Closing as this should be fixed in v0.2.1+10!
