### ISSUE TITLE
Articles are repetitive

### ISSUE THREAD

**Issue by Tealk** [hjiangsu/thunder#103]
**Description**  
When I scroll through the timeline it often happens that posts are displayed several times

**How to Reproduce**  

- Select All Posts
- Select Active
- just scroll a little through the timeline

**Expected Behavior**  
that the posts are simply displayed in the selected order

**Screenshots**  
![image](https://github.com/hjiangsu/thunder/assets/12276250/207072d5-0bf1-4ada-842e-82b3df39fd47)

**Device & App Version:**  
 - Device: Pixel6
 - OS: GraphenOS13
 - Version 0.1+7

**Comment by Fmstrat** [comment]
I've seen this too, I think it's due to the post being near a "page break" and it getting less popular, so while it was the last post on the API call, it became the first post on the next one.

A way to fix this is to filter out the display via ids currently in the displayed feed.

**Comment by hjiangsu** [comment]
Closing as its been released in v0.2.1+11!
