### ISSUE TITLE
Upvote/downvote sum for posts

### ISSUE THREAD

**Issue by trymeouteh** [hjiangsu/thunder#1051]
**Is your feature request related to a problem? Please describe.**
Upvote/downvote sum option for posts

**Describe the solution you'd like**
A setting to display Upvote/downvote sum for posts instead of upvote/downvotes

**Describe alternatives you've considered**
None

**Additional context**
Has been done for comments, please add this for posts.

https://github.com/thunder-app/thunder/issues/900

**Comment by K4LCIFER** [comment]
Are you referring to the posts in the feed, or when you open a post, or perhaps both?

**Comment by hjiangsu** [comment]
Just an update here: this is somewhat a work-in-progress with the changes that will be introduced here which allows you to customize the post metadata information on the feed: https://github.com/thunder-app/thunder/pull/1077

There's yet to be work done on the post page but it might follow suit afterwards!
