### ISSUE TITLE
Explore

### ISSUE THREAD

**Issue by trymeouteh** [hjiangsu/thunder#1053]
**Is your feature request related to a problem? Please describe.**
No way to explore an instance or the fediverse.

**Describe the solution you'd like**
In the search tab, when you do not have anything typed in the search box, you can explore all of the communities, users, posts and comments.

You can filter this out with the filters by only exploring the local instance, the entire fediverse, etc.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by K4LCIFER** [comment]
> No way to explore an instance

I agree -- this would be a very useful feature.

**Comment by hjiangsu** [comment]
> In the search tab, when you do not have anything typed in the search box, you can explore all of the communities, users, posts and comments.

I believe there is an endpoint which lists the communities (all, local, subscribed) for an instance via `/communities`. However, there is no endpoint that I know of which lists users or comments.

For posts, I believe they are already covered by using the Feed -> Local.

**Comment by CTalvio** [comment]
I've been thinking that as well as Trending, the top five federated communities could be shown in search, and should have an entry to a list where you can just scroll a list of all federated communities.

Browsing by comments is right there in the default webUI, so it's certainly a thing: https://sopuli.xyz/?dataType=Comment&listingType=Subscribed&sort=Hot

**Comment by micahmo** [comment]
Hey @trymeouteh, I just wanted to clarify your request. I believe the thing you're demonstrating, which we don't currently support, is the ability to see search results of all types mixed together (communities, users, posts, comments), without having to pick a specific type of thing to search. Is that right? If so, I believe that's covered by #1050. But please let me know if I misunderstood!
