### ISSUE TITLE
[Feature Request] Adding a Share button to a Post in the post list view, or alternatively adding an additional action button that is configuarable in the settings.

### ISSUE THREAD

**Issue by kringger** [hjiangsu/thunder#106]
**Is your feature request related to a problem? Please describe.**
Yes, Currently if you are scrolling posts, if you wish to share the post to someone, you need to first open the post, and then select the share button.  If you have the "Show full height images" settings option turned on, then the need to open the post in order to share is cumbersome. Having additional options in the post listing view would streamline user actions.

**Describe the solution you'd like**
I think adding an Share button or user configurable action button the to post in the post listing view (next to the Upvote, Downvote, and Star/Favorite options) would remove the need for users to click into a post to perform the desired action. If a user configurable action button is preferred, then in the app settings the user can choose what they would like this action to be. For example it could be share, visit author, visit community, hide, block, or even a 3-dot overflow menu with multiple options available.

**Describe alternatives you've considered**
None. Please see alternative solution above.

**Additional context**
The red box is the proposed location for this share button / user configurable action / overflow menu
![Screenshot_20230626-132548](https://github.com/hjiangsu/thunder/assets/35173157/6e60fec1-d9f6-4059-8134-ad6105692b3b)

**Comment by hjiangsu** [comment]
This will be added in the next release - heres a preview:

![image](https://github.com/hjiangsu/thunder/assets/30667958/e6a35158-df4f-44af-96dd-4d57a369d539)

![image](https://github.com/hjiangsu/thunder/assets/30667958/66b9aa73-db95-498e-8fd8-ea7ab1c31180)

**Comment by hjiangsu** [comment]
Closing as this should be fixed in v0.2.1+10!
