### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by Terkyz** [hjiangsu/thunder#11]
**Is your feature request related to a problem? Please describe.**
No. A just prefer a light mode for the app.

**Describe the solution you'd like**
A "Theme" option that lets me choose between light or dark theme in the app settings. 

**Describe alternatives you've considered**
I honestly don't know, I think it's something basic and simple but I'm not dev.

**Additional context**
I love your app!

**Comment by hjiangsu** [comment]
Hey, thanks for trying out the app! Definitely, theming is something I want to get to eventually. I'll keep in mind to add in an option for a light theme in a future release.

**Comment by hjiangsu** [comment]
Just an update on this issue - there will be a toggle in the settings for switching between light/dark modes in the next release! (the light mode might need some colours to be tweaked, but I'll wait for community feedback after its released to change it if necessary)

**Comment by hjiangsu** [comment]
This has been released in v0.2.0-alpha! I'll close this issue but let me know your thoughts!

**Comment by Terkyz** [comment]
I am definitely having problems with the light mode

1. Sometimes a green [tint](https://i.imgur.com/PwMpyMo.jpg) appears on the edges of the screen.

2. The app does not remember that I activate dark mode, when I activate it and re-enter it is in dark mode again.

**Comment by hjiangsu** [comment]
Thanks for testing it out! Yeah, i just looked at it and there's a slight bug where it doesnt fetch the theme setting when the app launches. As for the green tint, I have no clue what could be causing that to happen... I'll have to look deeper into that
