### ISSUE TITLE
Reload Feed Tab After Hitting 'Back' from Settings - iOS

### ISSUE THREAD

**Issue by martinjose** [hjiangsu/thunder#110]
**Description**  
When modifying General Settings, if you change any setting and then click the back navigation button in the top left, it will immediately reload the feed rather than returning you to the Settings tab. Additionally, the Settings icon will remain highlighted even though the Feed is being displayed.

**How to Reproduce**  
1. Go to 'Settings'
2. Click on 'General'
3. Modify any settings
4. Click 'Back' navigation option.
5. Feed is loaded and 'Settings' icon remains highlighted.

**Expected Behavior**  
The settings screen will be shown after clicking 'Back' navigation button.

**Screenshots**  
![The Back Navigation Button](https://github.com/hjiangsu/thunder/assets/16141594/6d9aed3e-27b9-4ab5-9024-cb359095f184)

![Error Case](https://github.com/hjiangsu/thunder/assets/16141594/dd187f2c-4bf7-48dc-a72c-130c0a08de42)

**Device & App Version:**  
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.5
 - Version 0.2.1+7

**Comment by hjiangsu** [comment]
Hey! This should hopefully be fixed in the next release!
