### ISSUE TITLE
Inconsistent haptic feedback when upvoting with gestures (android)

### ISSUE THREAD

**Issue by willbennett-kaltura** [hjiangsu/thunder#116]
**Description**  
When you upvote a post with a gesture, there's a nice haptic feedback response. When upvoting a comment, there is no such feedback.

**How to Reproduce**  
1. Open any post
2. Upvote using the slide gesture
3. No haptic feedback

**Expected Behavior**  
Consistency between posts and comments.

**Device & App Version:**  
 - Device: Pixel 7
 - OS: Android
 - Version: v0.21+8

**Comment by machinaeZER0** [comment]
I was going to file this as well, good catch!

**Comment by avasts** [comment]
I was going to create a request for this, glad I searched first. Haptic feedback on vote/reply/save would be very useful, I often have to double check to make sure I actually used the gesture.

**Comment by hjiangsu** [comment]
Yup, I accidentally undid the haptic feedback on comments on the last release - this will be fixed in the next one!

**Comment by hjiangsu** [comment]
Closing as this should be fixed in v0.2.1+10!
