### ISSUE TITLE
Alternative comment collapse behavior 

### ISSUE THREAD

**Issue by tunglith** [hjiangsu/thunder#119]
**Is your feature request related to a problem? Please describe.**
New comment collapse only closes the child comments and leaves the parent one fully open. This create cases where clicking on a long comment to collapse doesn't give any feedback and the user still has to scroll to skip long texts or comments including images.

**Describe the solution you'd like**
As it's an opinion thing, the best would be to put that collapsing behavior in a setting where we would have the original compact collapse of everything (with a one line preview of the parent comment) and the new behavior where the parent comment stays open. A third choice could be 3 line preview instead of one.

**Comment by theboomr** [comment]
Would strongly prefer this to be an option as well

**Comment by hjiangsu** [comment]
This has been added, and will come in the next release!

**Comment by krestenlaust** [comment]
> **Describe the solution you'd like** As it's an opinion thing, the best would be to put that collapsing behavior in a setting where we would have the original compact collapse of everything (with a one line preview of the parent comment) and the new behavior where the parent comment stays open.

It seems a little silly having an option for this, why not have an option for everything then. Though I can easily say that as I want the whole comment to collapse.

**Comment by theboomr** [comment]
> > **Describe the solution you'd like** As it's an opinion thing, the best would be to put that collapsing behavior in a setting where we would have the original compact collapse of everything (with a one line preview of the parent comment) and the new behavior where the parent comment stays open.
> 
> It seems a little silly having an option for this, why not have an option for everything then. Though I can easily say that as I want the whole comment to collapse.

I mean... yeah I like seeing options for everything 😅 that was one of my favorite things about Joey for Reddit, it was extremely customizable and configurable.

**Comment by krestenlaust** [comment]
> > > **Describe the solution you'd like** As it's an opinion thing, the best would be to put that collapsing behavior in a setting where we would have the original compact collapse of everything (with a one line preview of the parent comment) and the new behavior where the parent comment stays open.
> > 
> > 
> > It seems a little silly having an option for this, why not have an option for everything then. Though I can easily say that as I want the whole comment to collapse.
> 
> I mean... yeah I like seeing options for everything 😅 that was one of my favorite things about Joey for Reddit, it was extremely customizable and configurable.

Sure then. I've only used the official reddit app, I'm not used to being able to customize everything 🤷 Let's do it then. Forget I said something

**Comment by hjiangsu** [comment]
I think it makes sense to make this into an option - people have different opinions and preferences for how they prefer to do things, or they are simply used to one thing vs. another

I'd like to keep as much things as configurable as possible, so that everyone can customize the feel and look of Thunder to what they prefer! The only times that I might limit a potential option from being configured is if it has a large effect on performance, or it causes a lot of issues (excessive data usage, etc.)

**Comment by hjiangsu** [comment]
Closing as this should be fixed in v0.2.1+10!
