### ISSUE TITLE
Pull to refresh doesn't work on posts

### ISSUE THREAD

**Issue by tunglith** [hjiangsu/thunder#120]
**How to Reproduce**  
1. Go on a post
2. pull the page down to refresh it
3. Observe with disappointment as the post is not refreshed and the page jiggles in a mocking way

**Expected Behavior**  
Pulling on posts should reload it to show potential edits and new comments, the same way it happens on the home screen or in a community

**Comment by hjiangsu** [comment]
This has been added and will be in the next release!

**Comment by hjiangsu** [comment]
Closing as this should be fixed in v0.2.1+10!
