### ISSUE TITLE
Mark as read button on read inbox messages is not functional

### ISSUE THREAD

**Issue by tunglith** [hjiangsu/thunder#121]
**Description**  
In the inbox when looking at read messages, the "mark as read" tick appears but doesn't do anything

**How to Reproduce**  
1. Go to the inbox
2. Show all message
3. click "mark as read" tick on a read messages
4. Inbox refreshes with no changes

**Expected Behavior**  
Either the tick button should be removed or an alternative version should be used to mark messages as unread.

**Comment by hjiangsu** [comment]
I have hidden the checkmark in the next release! Might eventually make it so that you can set it back to unread but that'll be for the future

**Comment by hjiangsu** [comment]
Closing as this should be fixed in v0.2.1+10!
