### ISSUE TITLE
Ability to choose different sorting for comments

### ISSUE THREAD

**Issue by CTalvio** [hjiangsu/thunder#126]
**Is your feature request related to a problem? Please describe.**
Comments are only shown in a default order. There is no option to select, top, hot, new, etc.

**Describe the solution you'd like**
A dialogue for change comment sort type, same as main feed.

**Comment by guigs4** [comment]
I think I'm onto something.

I hope I can get it out before the weekend

**Comment by trymeouteh** [comment]
Would like to see option to sort comments by Hot, Top, New, Old and Chat just like on the Lemmy web UI but I will also like to a a [Forum](https://github.com/LemmyNet/lemmy-ui/issues/602) option.

**Comment by CTalvio** [comment]
> Would like to see option to sort comments by Hot, Top, New, Old and Chat just like on the Lemmy web UI but I will also like to a a [Forum](https://github.com/LemmyNet/lemmy-ui/issues/602) option.

You want to sort comments using "old"... but disconnect replies from the comments they are replying to?

**Comment by hjiangsu** [comment]
Closing as its been released in v0.2.1+11!

> Would like to see option to sort comments by Hot, Top, New, Old and Chat just like on the Lemmy web UI but I will also like to a a https://github.com/LemmyNet/lemmy-ui/issues/602 option.

We can bring discussion about the Forum option elsewhere so that I can clean up the issues page!
