### ISSUE TITLE
Infinity loading of feed on my instance

### ISSUE THREAD

**Issue by ChronosX88** [hjiangsu/thunder#128]
**Description**  
Any feed doesn't load at all, spinner just keeps spinning infinitely.

**Expected Behavior**:
Feed would load.

**Screenshots**  
![Screenshot_20230628-034101](https://github.com/hjiangsu/thunder/assets/8705683/9c1b8084-3ce9-469f-b9ae-5d598008a0db)

**Device & App Version:**  
 - Device: Google Pixel 6
 - OS: Android 13
 - App version: 0.2.1+8
 - Lemmy version: 0.18.1-rc.1
 - Instance: https://l.antiope.link

**Comment by ChronosX88** [comment]
Oh, it has fixed on its own for some reason too. But still bug exists.

**Comment by hjiangsu** [comment]
Hey! This is generally usually due to the instance taking a long time to respond back, or images/media taking a while to load

I'll see what I can do to add in some type of message to make it a bit more clear

**Comment by hjiangsu** [comment]
I'll close this issue since it feels like its due more to the instance than Thunder, but do let me know of suggestions that can help make this experience a bit better!
