### ISSUE TITLE
Reply button covers text

### ISSUE THREAD

**Issue by Tealk** [hjiangsu/thunder#130]
**Description**  
If it runs unfavorably and there are only so many answers that one cannot scroll but the last one is at the bottom, then the answer button covers parts of the answers.

**How to Reproduce**  
Find a post that has just the right number of responses.

**Expected Behavior**  
Good question, I can't think of a good solution right now, maybe an option to hide the button?
Actually it does not need it, if I want to reply to the topic then I have the buttons on top anyway and to reply to the comments I swipe.

**Screenshots**  
![image](https://github.com/hjiangsu/thunder/assets/12276250/238f12bc-9e8c-4157-97cd-783fad8d8adb)

**Device & App Version:**  
 - Device: Pixel6
 - OS: GraphenOS13
 - Version 0.2.1+8

**Comment by UniqueActive** [comment]
Related, the reply button also covers the share button if you get unlucky:

![Screenshot_20230628-154945_Thunder](https://github.com/hjiangsu/thunder/assets/27487663/a45596c3-4d43-48cc-9c3d-8f659d9d6b62)

**Comment by hjiangsu** [comment]
Oops, missed that edge case when I was implementing it - I'll see if I can fix that

**Comment by hjiangsu** [comment]
I think for now, what I'll do is:
- When you load up a post, the reply button is hidden
- If you start scrolling, then the button will appear
- Once you reach close to the end, the button will disappear again

**Comment by hjiangsu** [comment]
Closing as this should be fixed in v0.2.1+10!
