### ISSUE TITLE
Timeouts replace entire screen with error message

### ISSUE THREAD

**Issue by thepaperpilot** [hjiangsu/thunder#134]
**Description**  
Some servers are a bit overloaded and will time out on requests to upvote comments and posts. When that happens not only do you get a toast notifying you, but the whole screen gets replaced with the error as well, and you have to go to a previous page or refresh to fix it.

**How to Reproduce**  
1. Go to beehaw.org or other server that has regular timeouts
2. Upvote comments until you get a timeout 
3. Get the following toast and error page seen in the screenshots section 

**Expected Behavior**  
Keep the toast, revert the upvote, and let me continue reading the comments and try upvoting again

**Screenshots**  

![Screenshot_2023-06-28-11-05-25-59_ab870a90287380db09018f87a3131b61](https://github.com/hjiangsu/thunder/assets/3683148/f8444006-b902-4ee1-8598-f2bbf241f898)

**Device & App Version:**  
 - Device: Android OnePlus 9
 - OS: OxygenOS 13
 - Version: 0.2.1+8

**Comment by hjiangsu** [comment]
I think this should be fixed in the upcoming release - it'll only show the full screen error if there is an issue with fetching the post itself rather than comments

**Comment by hjiangsu** [comment]
Closing as this should be fixed in v0.2.1+10!
