### ISSUE TITLE
Toggle for title over image in feed view

### ISSUE THREAD

**Issue by Fmstrat** [hjiangsu/thunder#136]
**Is your feature request related to a problem? Please describe.**
When scrolling the feed view, titles are below the image. As the common behavior of image posting is a title that introduces or conceptualizes the image, having it come after the image reduces context, and can throw off cadence of a meme since it's an "introduction".

**Describe the solution you'd like**
A toggle to put the title on top in feed view

**Comment by Fmstrat** [comment]
Great example of where this can be problematic. The title for the RIF post looks like it goes with the image below it. I showed this to a few people and asked what the RIF post was about and they all responded with the image.

![Screenshot_20230628-195753](https://github.com/hjiangsu/thunder/assets/971474/e0b75ed7-ff51-46d0-929e-b35782893dcf)

**Comment by Fmstrat** [comment]
Another example that caught me this morning;)

![Screenshot_20230629-070117](https://github.com/hjiangsu/thunder/assets/971474/72d6bf7b-cf7b-4e60-ae8a-a1d7881c0331)

**Comment by hjiangsu** [comment]
I think that sounds like something that can be done!

I'll add in an option to move the title to the top

**Comment by tunglith** [comment]
Fully agree, was scared to say it ^^

**Comment by hjiangsu** [comment]
Closing this issue since it has been released in v0.2.1+11!
