### ISSUE TITLE
Increase visual separation of posts in dark theme

### ISSUE THREAD

**Issue by Fmstrat** [hjiangsu/thunder#137]
**Is your feature request related to a problem? Please describe.**
Due to the pack of contrast, posts in the feed view can tend to blend together in dark modes.

**Describe the solution you'd like**
One way would be to handle it like Sync (screenshot attached) where the post has a very dark gray background color, leaving a multi-pixel line of black (key part is height) between posts.

**Describe alternatives you've considered**
A million other visual designs

![Screenshot_20230628-185654_Sync Pro](https://github.com/hjiangsu/thunder/assets/971474/cb184850-0c50-47cf-994f-b01b8c3a6480)

**Comment by hjiangsu** [comment]
Hmm, I adjusted some colours for the divider and increased the width - let me know how it looks like:

I only have the default options in the screenshots, so not too sure how it'll change based on the material you themes:

Black theme:
![image](https://github.com/hjiangsu/thunder/assets/30667958/70f417da-2d47-403d-8a8e-9172db07a6bc)

Dark theme:
![image](https://github.com/hjiangsu/thunder/assets/30667958/faca1be9-1a27-4081-a475-9eab5766d3ce)

White theme:
![image](https://github.com/hjiangsu/thunder/assets/30667958/98d3254f-1550-45b4-8d1d-555af5c6ffea)

**Comment by hjiangsu** [comment]
For a bit more info - the way I did it above is that I take the background colour, and then lighten it or darken it based on light/dark modes.

I would have to play around a bit more with the material you themes to know how it would look across the board

**Comment by Fmstrat** [comment]
Thanks! Certainly seems to help. And thanks for the app, if I get some free time I'll help by contributing but unfortunately I'm tight on time atm :(

I do wonder if making the dark theme have a deep gray background with dark black lines between might help differentiate more from the black theme.

**Comment by hjiangsu** [comment]
>Thanks! Certainly seems to help. And thanks for the app, if I get some free time I'll help by contributing but unfortunately I'm tight on time atm :(

Yeah no worries!

> I do wonder if making the dark theme have a deep gray background with dark black lines between might help differentiate more from the black theme.

Hmm, it might, I think we can leave it as what the screenshot looks like for now and then gather community feedback?

**Comment by hjiangsu** [comment]
Closing as this should be fixed in v0.2.1+10!
