### ISSUE TITLE
Development environment missing `cider`

### ISSUE THREAD

**Issue by Fmstrat** [hjiangsu/thunder#139]
**Description**  
I decided to try to contribute, but being new to flutter I've hit a roadblock. I've installed dependencies, but when attempting to build with the build script it fails with:
```
$ dart scripts/build.dart
Checking if Flutter is installed...
Starting Flutter release builds for Android and iOS...

Fetching current version from pubspec.yaml...
Unhandled exception:
ProcessException: No such file or directory
  Command: cider version
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:487:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      buildRelease (file:///build/scripts/build.dart:20:39)
#4      main (file:///build/scripts/build.dart:120:3)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```
This can be reproduced with a clean environment using Docker and this Dockerfile:
```dockerfile
FROM fischerscode/flutter:3.12.0

# Set up the build folder
WORKDIR /build
USER root
RUN chown flutter:flutter /build
USER flutter

# Copy in prereq files
COPY --chown=flutter:flutter pubspec.* /build/

# Get deps
RUN flutter pub get

# Add all files
COPY --chown=flutter:flutter . /build

# Create env file
RUN echo "# comment" > /build/.env

# Build
RUN dart scripts/build.dart
```
Note; I'll be contributing the docker builder for others who wish to use it once I have this working.

**How to Reproduce**  
1. Use the above Dockerfile
2. Build with `docker build -f Dockerfile -t thunder-builder .`

**Expected Behavior**  
Successful build.

**Comment by hjiangsu** [comment]
Thanks for helping out! cider is a dart package used to help with releases and versioning! I think you have to install it globally using `dart pub global activate cider`

**Comment by hjiangsu** [comment]
I think this is resolved? Let me know if thats not the case
