### ISSUE TITLE
Change default timeline / Always opens 'local' timeline

### ISSUE THREAD

**Issue by krestenlaust** [hjiangsu/thunder#140]
**Is your feature request related to a problem? Please describe.**
Whenever I close the app and open it again, it resets to display 'local' timeline.

**Describe the solution you'd like**
I'd like to change default timeline setting.

**Describe alternatives you've considered**
Maybe just select the default timeline setting expressed in profile settings.

Can't find any duplicates, so I'm unsure of this is possibly a bug with my device 🤔

**Comment by hjiangsu** [comment]
Hmm, there was a setting added in the latest that gives you an option to select a default feed.

Can you double check to see if that is working?

**Comment by krestenlaust** [comment]
Didn't notice, thank you!
