### ISSUE TITLE
Auto-dismiss read posts

### ISSUE THREAD

**Issue by codenyte** [hjiangsu/thunder#1407]
### Is Your Feature Request Related to a Problem?

When I have already read a bunch of posts in my feed, and then refresh the feed, I see all my read posts.

### Feature Description

Option to automatically dismiss read posts after a reload

**Comment by micahmo** [comment]
You could possibly use the Lemmy feature for hiding read posts.

| ![image](https://github.com/thunder-app/thunder/assets/7417301/47741764-6ab7-4207-bf9a-3c400a61c518) |
| - |

The nice thing about this feature is that it syncs to your Lemmy account and also applies to the web UI.

(That is unless I am misunderstanding what you're looking for. 😊)

**Comment by micahmo** [comment]
Just to clarify, you should have "Show" "disabled" if you want to "hide" posts. (I'm assuming that's what you meant! 😊)

Two questions:
* Do your read posts appear in your feed on the web UI as well?
* Do your read posts appear grayed out in Thunder?

**Comment by micahmo** [comment]
No problem, happy to help! If you get a chance, next time you see the issue, can you pull up the web UI (even if it's on mobile)? The list of posts in your feed should be identical (assuming you're using the same sort type). That setting is a server-side thing, so we're not doing anything in Thunder to filter out posts.

Thanks for the feedback!

**Comment by hjiangsu** [comment]
> After experimenting around a little with the web UI, it appears to be an issue on the server side.

Hmm, could you clarify this? It seems to be working on my end on lemmy.world. I have "Show Read Posts" disabled in the Account Settings
