### ISSUE TITLE
External browser setting ignores links in comments

### ISSUE THREAD

**Issue by worsedoughnut** [hjiangsu/thunder#144]
**Description**  
"Open links in external browser" does not apply to links in comments

**How to Reproduce**  
1. Enable the "Open links in external browser" setting under Settings > General > Links
2. Open a thread and find a comment with a link to a webpage
3. Tap on the link
4. The link opens in the internal browser

**Expected Behavior**  
The link should open in the default browser (like it does correctly w/ links in thread titles)

**Video Reproduction**  
In this video, the thread link opens in the external browser, but the links found in the comments open in the internal browser.
https://imgur.com/a/qxd3jRr

**Device & App Version:**  
 - Device: Pixel 6 Pro
 - OS: Android 13
 - Version v0.2.1+8

**Additional Context**  
Feature referenced in #97

**Comment by hjiangsu** [comment]
I'll check it out - probably just missed it!

**Comment by hjiangsu** [comment]
A fix from @Fmstrat should hopefully have resolved this issue. There's a pre-release version v0.2.1-alpha.1+11 which contains these fixes. Try it out and let me know if the issue still persists!

**Comment by worsedoughnut** [comment]
Issue is fixed in the pre-release you mentioned, thanks!
