### ISSUE TITLE
Sharing post link (Local instance and your instance)

### ISSUE THREAD

**Issue by trymeouteh** [hjiangsu/thunder#1486]
### Is Your Feature Request Related to a Problem?

When you want to share the link of a comment that not on your instance, you have two options

- Share Comment Link
- Share Comment Link (My Instance)

This is not possible with posts

### Feature Description

Add the following options when sharing a link from a post

- Share Post Link
- Share Post Link (My Instance)

### Alternative Solutions

Only missing for posts. This feature exists already for comments, communities and users

**Comment by micahmo** [comment]
Hi @trymeouteh, I believe this feature is already available! It was added at the same time as it was for comments. The only time you might not see the additional option is if you're sharing a post which is already on your instance.

| Sharing a post from another instance | Sharing a post from my instance |
|--------|--------|
| ![image](https://github.com/thunder-app/thunder/assets/7417301/dc66ab12-8de6-40e3-b1e7-89f094925819) | ![image](https://github.com/thunder-app/thunder/assets/7417301/4cf44cd9-1d1b-4ae6-bf8f-55657da17446) | 

Can you let us know if you're having a different experience?
