### ISSUE TITLE
NSFW communities are not displayed in the "My Subscriptions" submenu.

### ISSUE THREAD

**Issue by Terkyz** [hjiangsu/thunder#15]
**Describe the bug**
I am subscribed to several NSFW communities and although the posts of these communities can be seen in the "Subscriptions" feed, I can't access them directly by searching for them in the "Subscriptions" feed.

**To Reproduce**
1. Subscribe to a NSFW community outside of Thunder.
2.  Open the feeds submenu
3. Search for NSFW communities

**Expected behavior**
That these communities are shown.

**Screenshots**
[This]() is the submenu of the communities to which I am subscribed in Jerboa, and [this]() is how it looks in Thunder.

**Smartphone (please complete the following information):**
 - Device: Samsung A10s
 - OS: Android 11
 - Browser Firefox
 - Version [Firefox version or Thunder version?]

**Additional context**
If you can please remove the links to the images in this feature request, I don't feel comfortable that anyone can see what communities I am subscribed to.

**Comment by hjiangsu** [comment]
@Terkyz could you confirm whether or not this is still an issue in the latest version v0.2.1+5?

**Comment by Terkyz** [comment]
I can confirm that it does work but there is something strange, I have two NSFW communities with the same name but of different instances and [domains](https://i.imgur.com/Z2NTHRq.jpg) but in the list of subscribed communities [only one](https://i.imgur.com/3kPDSxK.jpg) is shown.

**Comment by hjiangsu** [comment]
Hmm, I have no clue what could be causing that to happen.. do you know if the instances are federated/linked together? It could possibly be a federation issue but I would need to look deeper into the issue to figure out of thats the case or not

**Comment by hjiangsu** [comment]
I'll close this issue since I think it has to do with only 10 subscriptions being loaded at a time. Updates for this issue will be in #61 

If you think this is a separate issue, please let me know and I'll reopen this issue!
