### ISSUE TITLE
Ability to edit comments

### ISSUE THREAD

**Issue by CTalvio** [hjiangsu/thunder#158]
**Is your feature request related to a problem? Please describe.**
Add the ability to edit comments from thunder.

**Describe the solution you'd like**
I would like to be able to edit my comments. Obviusly this is coming eventually, regardless, but this is the most common reason why I'm still opening Jerboa now and then. Hence I'd love to have it sooner rather than later.

Perhaps "edit" should replace "reply" when gesture swiping on a comment that is your own?

**Comment by hjiangsu** [comment]
Yup, this is one of the top priorities after getting user profiles implemented!

**Comment by hjiangsu** [comment]
This is being worked on and will be available in the next release

**Comment by hjiangsu** [comment]
Closing as this should be fixed in v0.2.1+10!
