### ISSUE TITLE
Display vote counts for posts

### ISSUE THREAD

**Issue by CTalvio** [hjiangsu/thunder#159]
**Is your feature request related to a problem? Please describe.**
The votecount for a post, isn't actually displayed anywhere in the actual post view.

**Describe the solution you'd like**
Display the votecount somewhere.

![Screenshot_20230630-214955408](https://github.com/hjiangsu/thunder/assets/4365015/62bb8c15-606d-456d-bdb4-bba48a1a6a96)

**Comment by CTalvio** [comment]
Comment count, as well as separate up/down votecounts, would also be cool.

**Comment by hjiangsu** [comment]
Does this work for now?

![Uploading simulator_screenshot_6EEF07A4-A978-470A-B4B2-7962AC6E98A0.png…]()

**Comment by hjiangsu** [comment]
I'll mark this a fixed for now, but let me know if theres anything else

**Comment by CTalvio** [comment]
This works, though now time is displayed twice. There's a lot to consider displaying, like the language badge added in v18.

The post view will need work, but for now I can at least see the votecount when opening something that leads directly to a post.

**Comment by hjiangsu** [comment]
yeah, I do want to make it a bit better, but there's been so many other things on my plate and this is currently the fastest way to bring this!

If you have any suggestions or ideas on how to make it look, let me know and I'll see how it can be implemented in

**Comment by hjiangsu** [comment]
Closing as this should be fixed in v0.2.1+10! If you do have any suggestions for changes to how it is at the moment, feel free to create a new issue for this!
