### ISSUE TITLE
Error when subscribing from the community search screen

### ISSUE THREAD

**Issue by coslu** [hjiangsu/thunder#160]
I get the "Unsupported operation: Cannot modify and unmodifiable list" error when adding/removing subscriptions from the community search tab. The subscription/unsubscription goes through, but the list breaks. 

I am on Android using version [v0.2.1+8]. 

To reproduce: navigate to the search communities screen, type something in the search bar, on the list of communities that appear, click the plus or minus buttons.

**Comment by hjiangsu** [comment]
Yup, noted - I think the subscription still goes through, but that error just comes up because of the way I'm trying to update the UI to let someone know they performed that action

**Comment by hjiangsu** [comment]
This issue will be fixed in the upcoming release!

**Comment by hjiangsu** [comment]
Closing as this should be fixed in v0.2.1+10!
