### ISSUE TITLE
Make text copyable

### ISSUE THREAD

**Issue by Tealk** [hjiangsu/thunder#162]
**Is your feature request related to a problem? Please describe.**
Texts are currently not copyable, it is harder if you want to split single lines.

**Describe the solution you'd like**
That posts and comments can be copied.

See #161

**Comment by krestenlaust** [comment]
Related to later issue #251, but this issue is broader

**Comment by hjiangsu** [comment]
I think we can close this in favour of moving conversation to #251. A PR was merged recently to allow copying comments but more enhancements could be made to that functionality.

I'll close this for now but feel free to continue conversation in the other issue

**Comment by AppleSheeple** [comment]
@hjiangsu

#251 talks about **comments** text. Ability to select/copy/quote **posts** text is still lacking.
