### ISSUE TITLE
Simple way to access a user or community profile

### ISSUE THREAD

**Issue by Terkyz** [hjiangsu/thunder#17]
**Is your feature request related to a problem? Please describe.**
At this time there is no easy way to access a community by clicking on its name, or to access a user's profile, instead what doing that does is that the comment is minimized, and in the case of posts they are accessed.

**Describe the solution you'd like**
Being able to access a community by clicking on its name or a user's profile

**Describe alternatives you've considered**
I honestly can't think of any, although I know the app is in alpha and integrating this with the fediverse must be a pain.

**Additional context**
Forgive me for filling your Github with issues <2.

**Comment by hjiangsu** [comment]
Currently, there is one way to access a community directly by tapping on its name while you're on the feed page (although this isn't very obvious)

I do think this could be improved so your suggestions are welcomed!

**Comment by guigs4** [comment]
Should be somewhat trivial to implement after addressing #60

**Comment by hjiangsu** [comment]
This is currently in the works - here's a quick preview! feedback is appreciated

![image](https://github.com/hjiangsu/thunder/assets/30667958/2aedc84a-6321-446a-a6f6-b0cb04651ecd)

![image](https://github.com/hjiangsu/thunder/assets/30667958/9f3e3cb0-fe37-45b9-9157-7d7b648e9ba5)

**Comment by Terkyz** [comment]
It looks so damn awesome! Already looking forward for the new release!

**Comment by hjiangsu** [comment]
Closing as this should be fixed in v0.2.1+10!
