### ISSUE TITLE
Cannot download media using download media button

### ISSUE THREAD

**Issue by KhazAkar** [hjiangsu/thunder#171]
**Description**  
When trying to download media from post, nothing happens. By checking gallery app, also nothing new appears. Additionally, no indication is there that permissions are needed (I did that manually)

**How to Reproduce**  
1. Go to any post with media attached
2. Click on media to show media download button
3. Tap on this button
4. Nothing happens

**Expected Behavior**  
If permission is not granted, ask for it
If permission is granted, either allow for selecting saving folder using storage access framework (see Open Camera) or allow customization of folder name in DCIM folder.

**Screenshots**  
![Screenshot_20230702-095108_Permission controller](https://github.com/hjiangsu/thunder/assets/12693890/fb26aff2-e47b-4e4a-8269-c13b3660dcdc)

**Device & App Version:**  
 - Device: LG v30
 - OS: LOS 19 (Android 12)

**Additional context**
Fresh install, apk from github. Giving permission manually does not help.

**Comment by Poolitzer** [comment]
Worked fine for me on android 13. Fresh install, clicked on the download button, asked for permission and the button turned into a checkmark, the photo appeared in Pictures, top level folder.

**Comment by KhazAkar** [comment]
@Poolitzer interesting, worked for you on A13, not for me on A12 - not. What device BTW?

**Comment by Poolitzer** [comment]
Pixel 4a 5G

**Comment by hjiangsu** [comment]
I wonder if there was a change to how Android handles permissions between the versions. I'm not too sure off the top of my head what could be causing this

**Comment by hjiangsu** [comment]
A fix for this from @minicit may have resolved this issue - I have released a pre-release version v0.2.1-alpha.1+11 which contains these fixes. Let me know if its working for you or if there are still issues with this!

**Comment by KhazAkar** [comment]
@hjiangsu tested it and seems to work!
1. Access request work
2. Download works
3. Button changes from download button to tick
4. Only thing missing for me is where it saves. I found it in Pictures folder, but it's not indicated when downloading, for example as toast notification (on the bottom)

Thanks a lot! :)

**Comment by hjiangsu** [comment]
Closing as its been released in v0.2.1+11!
