### ISSUE TITLE
Can't login with kbin.social

### ISSUE THREAD

**Issue by acidrums4** [hjiangsu/thunder#177]
I really like this app for its minimal and well integrated interface. But for the life of me I can't manage to login with my kbin account.

Every time I put my kbin username, password and "kbin.social" in the instance field, I get this screen:

![Screenshot_20230702-081958_Trebuchet](https://github.com/hjiangsu/thunder/assets/513421/a65f7c27-84d1-450b-9284-da456761ab4e)

Not sure if I should put something different in the instance field, but am sure the credentials are correct. I've tried with v0.2.1+8 and v0.2.1+10 but did not have luck with any of them - the app shows this screen and freezes completely.

**Comment by hjiangsu** [comment]
Hey! Unfortunately, kbin support is not yet fully supported on Thunder. 

I'm focusing first on Lemmy support and adding all the core features there before adding in other platforms. Sorry about this 😅

**Comment by acidrums4** [comment]
Fair enough, I just wasn't aware of that (nor could find any mention of it anywhere)...

Still I like it so much. Will keep an eye on your app though and don't see myself using something else. Feel free to hit me if you need something related to graphic design about it (also do some web development, but still). Thank you so much!

**Comment by hjiangsu** [comment]
Yeah, definitely! I'm open to any suggestions with UI/UX that you find a little distracting or off!

I would like to see if it's feasible to add in kbin support in the future! (although it would be a bit further into the future for now)
