### ISSUE TITLE
Please add an "OLED dark" theme featuring #000000 backgrounds

### ISSUE THREAD

**Issue by brian-seek** [hjiangsu/thunder#18]
**Is your feature request related to a problem? Please describe.**
Would be great to have a fully-black theme option to decrease energy consumption/eye fatigue on OLED screens.

**Describe the solution you'd like**
Inclusion of a new theme that has #000000 background color, toggle-able in Settings.

**Describe alternatives you've considered**
"Get the hell over it," the app's new and you're doing a great job.  You may already have this in the pipeline.

**Additional context**

**Comment by hjiangsu** [comment]
Thanks for the suggestion! I was actually looking for a good way to integrate a better "OLED" theme as well but had a bit of difficulties with it (I'm not a UI/UX designer so my knowledge is somewhat limited when it comes to theming 😅)

This is something that I want to include in the future, along with a more robust theming system so that adding new themes is simple

**Comment by PcLover2** [comment]
Im currently installing flutter so I can test theming the app. I will let you know if i have found a good theme that fits the original theme and that has OLED colors. One thing i have to say is im not a huge fan of the purple, so i might make the oled theme with orange or blue

**Comment by PcLover2** [comment]
So after analizing the black.json file you currently use i noticed the purple was the tertiary color and the primary and secondary color are blue, wich i have never seen in the app. So might it be possible the app pulls its colors from the tertiary color?

**Comment by hjiangsu** [comment]
Hey, so.. I actually just worked on this LOL

I added in OLED dark mode in the settings on the `main` branch. I decided to use a different package to work with themes that seems to be easier to work with

**Comment by hjiangsu** [comment]
@PcLover2  What you can do is (if you're feeling like it), is to maybe extend upon the current theming to allow for more custom selection of themes!

After taking a quick look at the new package that is being used, it seems like it already has some pre-made themes which could be included somehow in the settings

**Comment by PcLover2** [comment]
Yeah im gonna check the new theming package but i dont know a lot about flutter so i wont be able to do a lot to help. Could you advise a way to learn flutter?

**Comment by PcLover2** [comment]
I cant find the flextheme package imported in the pubspec.yaml and main.dart still uses the old theming method? I dont really understand flutter so im really sorry if im saying something stupid

**Comment by hjiangsu** [comment]
Hey! No worries, any help is appreciated, even small ones! Before I give a longer reply, I just wanted to know what things you know so that I can maybe tailor my response accordingly.
- Do you know other programming languages? If you do, then what languages?
- How familiar are you with git/GitHub?

> I cant find the flextheme package imported in the pubspec.yaml and main.dart 

Did you pull the latest changes from the main branch? The theming logic should be in `core/theme/bloc` directory

**Comment by PcLover2** [comment]
I can program in python, and can build websites with html and css. I know the basics of git like pushing commiting and pull requests but thats about it. Im really interested in flutter and i would like to learn more about it. Since im working right now im gonna check the theme package this afternoon

**Comment by hjiangsu** [comment]
Yeah, for sure! I'll just write up a bit of info here to maybe help you understand how the theming works at the moment.

Flutter uses Dart (which I would say is somewhat in between Java/JavaScript) - you can dive deeper into how the syntax works here: https://dart.dev/language

As for the theming logic, theres a couple things that happen:

1. When you first start up the app, there's logic to fetch some of your settings (using SharedPreferences) to determine if you're using light/dark mode, and also if you've enabled the OLED dark theme: https://github.com/hjiangsu/thunder/blob/b7e10eb14ed16931685615cb857cb3f6a43168b8/lib/core/theme/bloc/theme_bloc.dart#L34-L51
2. Once your settings are fetched, I use a state-management library called `bloc` to keep track of certain things while the app is running. In this case, I keep track of whether the theme information was set correctly (`ThemeStatus.success`), if we should use the dark theme (`useDarkTheme`), and if we should use the the black (OLED) theme (`useBlackTheme`)
3. This state information then gets passed to the main.dart file which is where we initialize the app with the themes: https://github.com/hjiangsu/thunder/blob/b7e10eb14ed16931685615cb857cb3f6a43168b8/lib/main.dart#L74-L80
4. When you change a setting in the Settings page for the theme, the relevant setting gets saved, and then the app does a "refresh" to apply the new changes: https://github.com/hjiangsu/thunder/blob/b7e10eb14ed16931685615cb857cb3f6a43168b8/lib/settings/pages/general_settings_page.dart#L73-L82

Hopefully this is enough to get you a basic understanding of how theming works currently! The package that I'm using at the moment is [flex_color_scheme](https://pub.dev/packages/flex_color_scheme) (you can see it in action in `lib/core/theme/bloc/theme_bloc.dart`)

**Comment by hjiangsu** [comment]
Closing this issue as it has been released in v0.2.1+6
