### ISSUE TITLE
[Feature Request] Share images through Android Sharesheet

### ISSUE THREAD

**Issue by jdevowe** [hjiangsu/thunder#181]
Having used RIF is Fun until recently, I would prefer to share images in The directly to another app via the Android Sharesheet instead of a link to the lemmy post. Current option is downloading from Thunder and sharing from an external app (such as sharing from Gallery to a contact in Messages).

Possible implementation: Select share on a post, tap and hold on a post title, or tap and hold on the image itself to have options appear in a menu to share a link to the post or the image itself. "Share link,"" "Share image".

**Comment by jdevowe** [comment]
Looks promising! Can't wait to try it out in the release that features it.

**Comment by micahmo** [comment]
Hey @hjiangsu, thanks for adding this in the latest alpha! It works great and it's really nice to have.

My only comment would be that I was expecting it to share the media itself, not a link to the media. I suppose that may require downloading it first, but I will say some Reddit apps have that function.

Thanks again for the update!

**Comment by hjiangsu** [comment]
> My only comment would be that I was expecting it to share the media itself, not a link to the media. I suppose that may require downloading it first, but I will say some Reddit apps have that function.

Oops, hmm - I can take a look to see if theres a way to do that! Do you happen to know if the other Reddit apps had to download the media first before sharing it? That'll help me figure this out a bit better

**Comment by micahmo** [comment]
> Oops

What you added is great, btw! Didn't mean to take anything away from that!

> Do you happen to know if the other Reddit apps had to download the media first before sharing it?

Unfortunately I don't know offhand. The one I used wasn't open-source but I could try to find one that is. I suppose the media is in memory somewhere, but maybe you're just assigning a URL to a control and letting it handle that?

**Comment by hjiangsu** [comment]
Alright - I'll do some tests when I have the time and see if its possible to do what you described!

**Comment by jdevowe** [comment]
> Alright - I'll do some tests when I have the time and see if its possible to do what you described!

I find some info regarding using three Android Sharesheet for sending binary data such as images. I'm in the early stages of learning to code and I think this is beyond me at the moment.

https://developer.android.com/training/sharing/send

Under heading "Send binary data."

**Comment by hjiangsu** [comment]
Thanks - that'll come in a bit useful!

**Comment by hjiangsu** [comment]
Closing this issue since it has been released in v0.2.1+11!
