### ISSUE TITLE
Suggestion for Post View layout - Discuss?

### ISSUE THREAD

**Issue by CTalvio** [hjiangsu/thunder#184]
I edited up a layout change that would display some info I'm missing, while staying within the design of the app.

![image](https://github.com/hjiangsu/thunder/assets/4365015/78bbcdf4-b795-4eb7-911e-36d5522f41fc)

Title and post content come first, with nothing else. If a language badge were to be displayed, I would perhaps append it to the title, or have it sit between title and content. But its not really necessary, a reader can tell what language a post is in, regardless.

User and community with the addition of "in" so as to make clear which is which. Consider using the word "to" in order to match with Lemmy webUI. 
![image](https://github.com/hjiangsu/thunder/assets/4365015/02ba85fa-d991-470a-b68e-9049f3905f86)
I also feel their location below the content makes more sense, as they are both potential points of user interaction, and as such end up closer within reach of one-handed-thumb interaction.

Lastly, I would like vote counts to be displayed separately in the post view, as well as on comments (when there are downvotes). Combining and hiding the separate counts was something reddit did and lemmy explicitly does not. I'd like for Thunder to embrace that.

**Comment by CTalvio** [comment]
Addition, edited posts should have the clock change to a pen.

Having a pen appear next to the time on comments that have been edited, would also be nice.

**Comment by CTalvio** [comment]
Another thought. Thunder should eventually display and link to any cross-posts.

**Comment by hjiangsu** [comment]
I like to overall design changes - do you think its better to keep the feeds the same, or should it also use the changes you mentioned here?

**Comment by CTalvio** [comment]
I think the feed view already displays all the details needed. One of the reasons I like Thunder so much is the restrained minimalism.

When scrolling past posts, the posting user is not strictly necessary info, but the community and instance is. As it should be possible to act on it in the form of blocking or subscribing without opening the post or the community.

The votecount could be kept as a single number, as it is more glance-able. If the numbers were displayed with the buttons, you'd only be able to do so when they are enabled in normal view. Having it displayed together with the comment count and post time makes sense, and I like how compact it is.

One thing you might want to add to the post view, is a subscription button in the top right, same one as on community pages. Having it displayed in posts would be yet another way to sub to interesting communities, but more than that, it would serve as way for users to check/notice if they are looking at a duplicate community, that they might ALSO want to sub to, as the button status would differ depending on whether they are already subbed.

**Comment by hjiangsu** [comment]
Sounds good! Thanks so much for the contributions - I'll have a quick look over the PR later today and let you know of any changes (if any)

Thanks :D

**Comment by CTalvio** [comment]
Crosspost and edit indicators remain, byt the layout change is done, so closing.
