### ISSUE TITLE
The ability to delete, change my message, and what's in the screenshot.

### ISSUE THREAD

**Issue by Wjxfi** [hjiangsu/thunder#189]
![e0ca8bdd-13a9-448a-97ab-5140ea0c1acd.jpg](https://github.com/hjiangsu/thunder/assets/113500363/4ceeb171-e5b4-4ce5-a936-ff4d62502231)

![571b2f52-cbd1-414c-8365-04a802a78241.jpg](https://github.com/hjiangsu/thunder/assets/113500363/d68ca13b-482e-4176-8a6f-28e3fe67576b)

**Comment by hjiangsu** [comment]
Hey! Could you make each separate point into a new issue? This way it'll be easier to track each individual feature as opposed to multiple features!

**Comment by krestenlaust** [comment]
@Wjxfi if you can just make a short list of each feature you are suggesting, then I can make the issues, if you'd like.

I am not sure what other features your are suggesting other than deleting, as you can edit by swiping. I also don't understand where the screenshot is from 🤔

**Comment by hjiangsu** [comment]
I will close this since it should be split up into separate issues for each feature request. Do feel free to create a new issue for each individual request!

**Comment by krestenlaust** [comment]
Just a suggestion, but in the future you could choose to close issues like this one as a dupe/cant repo, so people don't find this issue and believe it's been resolved :)

**Comment by krestenlaust** [comment]
I don't understand, what the disagreement is with my comment?
