### ISSUE TITLE
Make compressed comments visible with a count

### ISSUE THREAD

**Issue by Fmstrat** [hjiangsu/thunder#190]
**Is your feature request related to a problem? Please describe.**
When compressing comments and having the parent comment still displayed, you can't tell the comment is compressed.

**Describe the solution you'd like**
When a comment is compressed but still displayed, put a numerical indicator for how many comments were compressed underneath.

**Comment by hjiangsu** [comment]
This should be possible to do fairly easily - do you think its better to check for the length of the direct replies, or the total number of replies (including replies to replies)

**Comment by Fmstrat** [comment]
Personally I'd do total vs direct, but I have no real reason for that beyond showing volume. It would probably be useful on the fully compressed view, too.

**Comment by hjiangsu** [comment]
Closing this issue since it has been released in v0.2.1+11!
