### ISSUE TITLE
Filter out newly fetched posts that are already in view from previous fetch.

### ISSUE THREAD

**Issue by ajsosa** [hjiangsu/thunder#192]
### Problem
It's possible for there to be duplicate posts in the view. This happens because sometimes, the next Lemmy post fetch may contain an existing post that you had received in the previous post fetch.

### Solution
Check if post already exists in view before appending the new incoming posts.

### Possible Implementation
I have no Dart, Flutter, or Android/iOS dev experience. But I managed to hack a fix for a personal build and it seems to be working. I basically keep a Set of keys derived from post's user, title, and community in `community_bloc.dart`. I check against this Set when new posts are fetched, and if the key exists I don't append the post. I don't know enough about Lemmy to know if that's a good way to identify a post. Perhaps there is a unique ID present I don't know about. Either way, ignore this implementation idea if it sounds dumb for how to handle this. Thanks for all the work you've put into this app so far. It rocks! :)

### Example of Issue
![dupe-example](https://github.com/hjiangsu/thunder/assets/41923324/1e4baf06-3495-47c4-a5ce-10cd06502940)

**Comment by hjiangsu** [comment]
Each post should have an associated post id that should be unique. However, in this situation where we see duplicates, I'm not sure if the instance posts are actually the same post with the same id, or if theres duplicates with different ids.😅

Depending on which one it is, we could go with either a simpler approach of doing a filter based off the post id (first case), or we could use the method you described (second case)!

**Comment by ajsosa** [comment]
Now that I figured out how to debug Flutter apps. I did some digging into using `PostViewMedia.postView.post.id` as the key to keep track of. Did some spot checking and it looks like the `post.id` is unique to that post. So you should be good moving forward with that instead.

**Comment by hjiangsu** [comment]
Feel free to make a PR for it if you wish! That would be great :D

Make sure to use the `develop` branch for any PRs since that contains the latest changes

**Comment by ajsosa** [comment]
This was addressed by the now merged https://github.com/hjiangsu/thunder/pull/212.
