### ISSUE TITLE
Post shows negative time ago (probably related to timezones)

### ISSUE THREAD

**Issue by krestenlaust** [hjiangsu/thunder#194]
**Description**  
This post has a negative time-ago time.

**How to Reproduce**  
- Use a different time zone, I believe. My time zone is +2 (Denmark)

**Screenshots**  
![Cropped screenshot of the post in question](https://github.com/hjiangsu/thunder/assets/17174333/a7baea0a-0f19-4691-8621-31cb0aef4dde)

**Device & App Version:**  
 - Device: Oneplus 6T
 - OS: Oxygen OS 11.1.2.2 (Android 11)
 - Version: v0.2.1+8

**Additional context:**
Viewed at 12:00 my time (the time of this issue)
[The post in question](https://kbin.dk/m/nyheder@feddit.dk/t/5709)

Edit: Added new information

**Comment by krestenlaust** [comment]
https://kbin.dk/m/nyheder@feddit.dk/t/5709

**Comment by hjiangsu** [comment]
This is most likely due to timezone issues as you mentioned. How often does this issue occur?

When I get a post back from the lemmy instance, I convert your time (which I think should be based off your device) to UTC time, which is what the post's time should be in. Then convert that into a more digestible form (minutes, hours, days, etc)

https://github.com/hjiangsu/thunder/blob/e2fc98afdd39030ac1c6a4e8edf080c7858cf5b3/lib/utils/date_time.dart#L10-L22

**Comment by micahmo** [comment]
I'm not sure that this is an issue with Thunder. I correlated a couple posts with future publication times to the web page, and the same issue is shown.

| Thunder |
| - |
| ![image](https://github.com/hjiangsu/thunder/assets/7417301/e3255682-05af-41d4-a9e6-0647bcc8c890) |

| lemmy.world |
| - |
| ![image](https://github.com/hjiangsu/thunder/assets/7417301/de68fb29-847b-4ee8-8314-e1574e59d846) |

**Comment by krestenlaust** [comment]
> This is most likely due to timezone issues as you mentioned. How often does this issue occur?

This is the first time I've experienced it, and I've had the app for maybe 10 days 🤔

**Comment by hjiangsu** [comment]
This might not be an issue that is fixable within Thunder - we could make it so that it shows the time in the future, but I think that would still be confusing if someone were to see `+97m`

**Comment by hjiangsu** [comment]
I'll close this for now, but feel free to continue conversation

**Comment by krestenlaust** [comment]
Shouldn't it closed as "can't repro"? I'll look up this issue when it happens again

**Comment by micahmo** [comment]
If we're splitting hairs and/or adding tags, I would vote for something like `lemmy-issue`. We can repro it, but it happens on the web too.

**Comment by krestenlaust** [comment]
Oh okay, then it's a different issue. Didn't realize. Having a tag for that would be helpful as well. It would allow maintainers to follow up on these kinds of issues.

This issue is a bad example though, as it's entirely on the backend then and it should resolve itself once that's been resolved.
