### ISSUE TITLE
Improved feedback on swiping actions (UX)

### ISSUE THREAD

**Issue by krestenlaust** [hjiangsu/thunder#195]
**Is your feature request related to a problem? Please describe.**
The recent update increased the threshold for a swipe to occur, which has thrown my highly trained muscle memory awry. It's is difficult to now whether you've dragged the slider far enough to trigger an action.

**Describe the solution you'd like**
Suggestions:
- ~~Vibration: Subtle vibration when a threshold has been met.
For example, upvoting would trigger one vibration, and downvoting would first trigger one vibration (upvote), then another.~~
- Visual element: Slight change in color
Tinting the color slightly would also be a great help
- Visual element: Some kind of vertical line or mark at the top and bottom.
This would be inside the orange, blue, green or purple box with an icon in it. Add some kind of small mark to show the threshold. This would make it easier to 'train' the correct dragging distance.

**Describe alternatives you've considered**
I'm not entirely sure about tinting.

**Comment by hjiangsu** [comment]
> Vibration: Subtle vibration when a threshold has been met.

This should have been added back im 0.2.1+10

> Visual element: Slight change in color
Tinting the color slightly would also be a great help

I like this approach a lot, I'll see if I can add it!

**Comment by krestenlaust** [comment]
I'm afraid that there's no vibration on my (Android 11) phone. I'll probably create a bug report later today then

**Comment by krestenlaust** [comment]
Another spin on the tinting is to make the arrow white (or whatever the opposite is to the theme), and when it's far enough, it can be the right color. The inner option would always have the correct colored arrow

**Comment by hjiangsu** [comment]
> I'm afraid that there's no vibration on my (Android 11) phone. I'll probably create a bug report later today then

This may be a dumb question from me, but vibrations are enabled on your phone right?

**Comment by hjiangsu** [comment]
General thoughts on this? Pretty much, the background colour changes opacity until the first action is triggered. The icons for the actions also only show up when corresponding thresholds are reached


![comment_voting](https://github.com/hjiangsu/thunder/assets/30667958/25dbc63e-c424-48dd-98d8-5aeeb8a6be51)

**Comment by krestenlaust** [comment]
Apparently, the vibration is hidden behind an option that enables vibrations on every click in my system settings. I'll make due without then 😅

**Comment by hjiangsu** [comment]
Dang - I'm not sure if theres a way to override the system settings for vibration feedback unfortunately.

If you were to turn on the enable vibrations, can you confirm that it works? I don't have a physical android device so it would be nice to confirm that behaviour!

**Comment by krestenlaust** [comment]
> General thoughts on this? Pretty much, the background colour changes opacity until the first action is triggered. The icons for the actions also only show up when corresponding thresholds are reached
> 
> ![comment_voting](https://user-images.githubusercontent.com/30667958/250577001-25dbc63e-c424-48dd-98d8-5aeeb8a6be51.gif)

Looks great!

I might make another issue about having a maximum pull distance, as I believe it would make it more snappy, rather than allow you to keep pulling

**Comment by krestenlaust** [comment]
> Dang - I'm not sure if theres a way to override the system settings for vibration feedback unfortunately.
> 
> If you were to turn on the enable vibrations, can you confirm that it works? I don't have a physical android device so it would be nice to confirm that behaviour!

Yes, it works!

**Comment by hjiangsu** [comment]
> Yes, it works!

Thanks for confirming!

**Comment by hjiangsu** [comment]
I have just released a pre-release version v0.2.1-alpha.1+11 which contains the changes I mentioned, including the ability to also customize the gestures - let me know what you think and provide any feedback if possible!

**Comment by krestenlaust** [comment]
> Why is there no option to turn off a single swipe option? e.g. **none**, Upvote, Downvote, Save Replay

I've made it into a separate issue now #217

**Comment by hjiangsu** [comment]
Closing this issue since it has been released in v0.2.1+11!
