### ISSUE TITLE
Android - Can't login to Lemmy.world 

### ISSUE THREAD

**Issue by dephunk** [hjiangsu/thunder#2]
"Oops, something went wrong! SocketException: Failed host Iookup: 'lemmy.world' (0s Error: No address associated with hostname, errno = 7)"

This is the error I'm getting.

UI is looking nice otherwise for a first alpha!

**Comment by abalteaux** [comment]
I have the same issue with both beehaw.org and lemmy.ca.

**Comment by s-hgr** [comment]
For me the issue happens with discuss.tchncs.de .

**Comment by deepu2** [comment]
I think the internet permission was not declared so it cannot access internet

**Comment by bqv** [comment]
Lmao

**Comment by realeatham** [comment]
You can't login to any instance or see any posts.

**Comment by hjiangsu** [comment]
Noted! Thanks for pointing that out - unfortunately I currently don't have access to a physical Android device so all testing was done through the simulator 😅

**Comment by deepu2** [comment]
> Noted! Thanks for pointing that out - unfortunately I currently don't have access to a physical Android device so all testing was done through the simulator 😅

Yeah, the thing is it adds the Internet permission for debug builds automatically but won't do the same for main builds.

**Comment by hjiangsu** [comment]
Just released a new version which hopefully fixes that internet permission issue, and adds in a few other fixes as well!

Let me know if this issue is resolved!

**Comment by pabloscloud** [comment]
Yes, fixed now. Thanks! 💙
