### ISSUE TITLE
Increase blurriness for NSFW posts in feed

### ISSUE THREAD

**Issue by tunglith** [hjiangsu/thunder#214]
**Is your feature request related to a problem? Please describe.**
Okay so the NSFW blur is a bit to clear, it's okay when you're close to the phone but here's the thing ; blurred and pixelated things appear more clearly when viewed at a distance. So if you squint or are 2-3 meters away, you can definitely tell what's in the pictures and those people are exactly whom I am blurring my NSFW for.

**Describe the solution you'd like**
More blurry, less horny.

**Comment by tunglith** [comment]
Also exiting a blurred NSFW post unblurs it for just a second before going back to the feed.

**Comment by krestenlaust** [comment]
This has already been adjusted before. Maybe an option in blurriness is preferred then, a 3-way-toggle could be a good idea (no blur, slight blur, heavy blur).

**Comment by machinaeZER0** [comment]
That's funny - I use compact view and I was thinking earlier today that the thumbnails are so blurred I really had no idea what the original images were, hahah. I personally wouldn't mind if compact thumbnails were less blurry, but having switched to non-compact view I can see where you're coming from on that front!

**Comment by hjiangsu** [comment]
Linking this PR as it has a tweak to the blur values: https://github.com/hjiangsu/thunder/pull/225

**Comment by hjiangsu** [comment]
Closing this issue since it has been released in v0.2.1+11!
