### ISSUE TITLE
Changing sort modes or refreshing resets view to Local Posts

### ISSUE THREAD

**Issue by jordan1776** [hjiangsu/thunder#22]
**Describe the bug**
Changing sort modes or refreshing the feed resets view to Local Posts

**To Reproduce**
1. Go subscriptions or All Posts
2. Change sort to anything
2 alternative. Refresh feed
3. See error

**Expected behavior**
changing sort or refreshing shouldn't affect the feed loaded 

**Smartphone (please complete the following information):**
 - Device: Xperia 1 II
 - OS: Android 11

**Comment by hjiangsu** [comment]
Hey! I also noticed that during development and have applied some fixes to it. The "refresh feed" bug should be fixed in an upcoming release

**Comment by hjiangsu** [comment]
This should hopefully be fixed in v0.2.0-alpha! I'll close this issue for now, but do let me know if it is still occurring

**Comment by jordan1776** [comment]
This refresh bug is fixed but it seems like refreshing the page changes the sort to hot, I'll put an issue in
