### ISSUE TITLE
more post view modes like jerboa and reddit

### ISSUE THREAD

**Issue by realeatham** [hjiangsu/thunder#23]
A setting for changing the post view mode.

Jerboa modes for inspiration (copy them)
![Screenshot_20230619_165737_Jerboa for Lemmy](https://github.com/hjiangsu/thunder/assets/136866675/420085b7-878b-45cc-9fc7-c4b94bbc490c)
![Screenshot_20230619_165708_Jerboa for Lemmy](https://github.com/hjiangsu/thunder/assets/136866675/1aed2ca9-8d8c-4bb1-b416-af38cd55f7d0)
![Screenshot_20230619_165702_Jerboa for Lemmy](https://github.com/hjiangsu/thunder/assets/136866675/f902e925-7e7c-4d4b-9272-08c1a0e72451)

**Comment by jordan1776** [comment]
Probably the big ones for views are:

- a (very compact) list view
- a (slightly less compact) small card view
- a 2 column gallery/image focused view (w/ or w/o context)
- The current large card view

I would try looking at Relay, Boost, and Sync for inspiration.

**Comment by hjiangsu** [comment]
Thanks for the suggestions and screenshots, I'll keep them in mind for future releases!

**Comment by hjiangsu** [comment]
Update on this: a compact view is being worked on! Here's an early preview:

<img width="379" alt="image" src="https://github.com/hjiangsu/thunder/assets/30667958/2315d2a6-cdfa-418d-8c64-da14584152bf">

**Comment by hjiangsu** [comment]
I will close this issue as a compact view has been added in the latest release v0.2.1+6.

However, if there are more preferred views, feel free to open up a new issue for them (preferably separate issues for each different view)!
