### ISSUE TITLE
Android - stuttering issues while scrolling?

### ISSUE THREAD

**Issue by any1th3r3** [hjiangsu/thunder#24]
**Describe the bug**
Stuttering happens (intermittently) while scrolling (up and down) on Android.

**To Reproduce**
1. Open the app.
2. Begin scrolling.
3. Stuttering will eventually happen.

**Expected behavior**
I wouldn't expect stuttering, outside of an "abrupt" stop when loading new content.

**Screenshots**
N/A.

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: GrapheneOS
 - Version: Android 13

**Additional context**
This seems to mostly be happening towards the bottom of the "infinite feed" and close to posts with images, however not specifically when hitting the actual bottom of the feed, so to speak.  
And afaict scrolling within threads with lots of comments and/or images seems to stutter as well, albeit to a lesser degree.

**Comment by hjiangsu** [comment]
Hey! Yeah, there's still quite a few optimizations that could be done to improve the performance of the app. A few things are probably happening here:
1. When the user scrolls to roughly 80% of the feed, there is fetching done in the background which might be contributing to the lag
2. With images especially, right now it's not that well optimized to handle a large list of images. I do have an idea which can hopefully improve the performance of images (reducing the resolution and size of the image when its in the feed, and only display the full resolution when the user taps on the image)

These improvements will happen (whenever possible) as more progress is done on the app!

**Comment by hjiangsu** [comment]
@any1th3r3  Just checking in to see if there's been any improvements to performance

**Comment by ShizuKoto** [comment]
> @any1th3r3 Just checking in to see if there's been any improvements to performance

Just went on an instance with 0.0.18 on it and the more I scrolled, the worse it got. It got to the point where it felt like 1fps.
I had similar issues with the OG Reddit App which made me use 3rd party apps for Reddit in the first place.
Also I've noticed my phone getting pretty warm while browsing Lemmy thru Thunder.
Might all be connected.

**Comment by hjiangsu** [comment]
Alright thanks for the update - i did notice a bit of that too

A few things here are potentially at play:
- For images, theres no "preview" sizes as far as I could tell. When I query the lemmy API, it sends back a link to the full image which is not the best performance-wise
  - The best outcome would be if the API returned back images at different resolutions, so that the correct one can be used, and reduce memory usage for storing the full size of the image 
- For images, the lemmy API doesn't provide back the width and height, which is used to reduce jank when scrolling. Because theres no width and height information available, the current implementation requires me to download a part of the image in order to be able to determine the width/height

**Comment by hjiangsu** [comment]
Just curious, which view are you using? compact, the normal default view, or the full-height image view?

**Comment by ShizuKoto** [comment]
Is it possible to load images asynchronous?
Or maybe it's possible to download smaller batches of posts in order to reduce the impact on the network and processing?

**Comment by ShizuKoto** [comment]
> Just curious, which view are you using? compact, the normal default view, or the full-height image view?

Full height. I don't like having to click on the posts to be able to sell all the meme or picture attached to it.

**Comment by hjiangsu** [comment]
> Is it possible to load images asynchronous?

I think it is currently loading images asynchronously - it creates futures for each post when fetching image data, and then processes all those requests at the same time in the background

> Full height. I don't like having to click on the posts to be able to sell all the meme or picture attached to it.

Ahh yeah, then in that case, it's most likely something with the images themselves and how large they are/resolution. The full resolution of the image is stored in memory, so if there are a lot of images, and each image has a large resolution/size, then memory usage spikes. I'll take a look when I can to see what can be done to maybe reduce performance impact from that, but the best solution would be for the lemmy API to provide back image metadata (width/height) along with the image URL

**Comment by ShizuKoto** [comment]
How would metadata solve the issue of the app possibly loading multiple pictures at the same time in the background?🤔
I think a better solution would be for the API to offer a way to resize the images on the fly maybe?
Meaning.. you telling the API "hey, give me this pic but it shall have a width of not more than 600px" or something like that.

Another idea would be to load the pics one after the other queueing them up. I believe that's how Infinity used to handle this.

**Comment by hjiangsu** [comment]
Yeah I think if the instance has different resolutions, that would also greatly help with the lag and stuttering we're seeing right now

The image metadata helps in a sense that I don't have to rely on the logic for fetching height/width of an image by downloading it. This reduces the amount of network calls the app makes (in which case, it makes two calls to fetch the image, once for the beginning of the image data for the first x number of bytes which contains the metadata, and then again to fetch the full image file)

**Comment by ShizuKoto** [comment]
I've used the app for a little bit now after having it properly closed. 
It quickly grew to 2.3GB memory usage. It does seem to hold all images in memory? 
Is it an option for you to drop the images from memory after you scrolled past them? They'd have to be re-downloaded after scrolling up again but that shouldn't be an issue, right?

**Comment by hjiangsu** [comment]
Yeah, I'm currently looking into ways to reduce this - it seems that by default, Flutter holds all the images in a list in memory, so if you start scrolling longer and longer, it causes the RAM to grow in size

This is a relevant StackOverflow post on it: https://stackoverflow.com/questions/66343674/images-in-listview-are-not-released-from-memory-when-out-of-view

I can see if its possible to implement the suggestions that are in that SO post and hope it produces better results

**Comment by hjiangsu** [comment]
Okay, so after doing some experimenting with it, I managed to get it to work

I did a really quick test of it and it seems to provide better performance, but it might need a bit more testing

**Comment by ShizuKoto** [comment]
Sounds awesome! I hope your tests are successful as your app is the best one among all the apps I've tested and I'd like to settle on it 🫡👍

**Comment by hjiangsu** [comment]
Update - I just released v0.2.1+8 which has the changes I mentioned.

@ShizuKoto Could you help out and see how the performance is like with this new update? I know theres still a bit of stuttering going on, but hopefully it has improved!

**Comment by ShizuKoto** [comment]
I'll check it right away!

**Comment by ShizuKoto** [comment]
Soo, I was continuously scrolling in the latest version and good news first:
It didn't crash bc anymore.
But
It started off with a pretty choppy frame rate and only got worse.
I'd say it started with 15-20fps
The more I scrolled the more memory was used.
However, memory usage did never exceed 2.9GB.

The App froze for 30sec after hitting 2GB memory but kept going with 2-5fps afterwards.

Really it doesn't feel like the pics are being loaded async. They are there as soon as I scroll further - it feels more like the stuttering comes from every pic being loaded which freezes the app all together while the download is going.

**Comment by hjiangsu** [comment]
Hmm okay, so slight improvement but still a lot of work to be done on that performance wise

I think one big contributing factor (thats outside of my control) is being able to resize the images into smaller resolutions - at least for the feed page, and then use full resolution when tapping to preview the image

> Soo, I was continuously scrolling in the latest version and good news first:
How fast would you say you were scrolling? The speed of that might change how performant it is

> It started off with a pretty choppy frame rate and only got worse.
Just to clarify, this was after scrolling through a bit right? Or was it at the very start?

I'll have to dig deeper then and see if maybe theres something else I can do (or maybe someone that has a bit more knowledge on this can do)

**Comment by hjiangsu** [comment]
I'm pinning this issue and adding the help-wanted tag to see if anyone from the community can further help with this issue!

**Comment by ShizuKoto** [comment]
The choppiness appeared after scrolling like 20 posts.
Also my phone has 8GB native and 4GB "plus memory" which is just using 4GB of internal storage.
My home wifi has 1GBit/s downstream with at least 500MBit/s reaching my phone thru Speedtests.

If you wish I can make a screen recording of what I'm experiencing in order for you to maybe understand better.

**Comment by hjiangsu** [comment]
> The choppiness appeared after scrolling like 20 posts.

This was 20 posts of images? or was it a mix of images and text, etc?

I have an idea of what you mean by the stuttering - I've noticed it myself too

**Comment by ShizuKoto** [comment]
> This was 20 posts of images? or was it a mix of images and text, etc?

It was a mix of images and text.

**Comment by hjiangsu** [comment]
Alright, I tried to play around with the code a bit more to see if I can maybe improve performance further. Since I can't upload APKs here directly, this is a link to a build that I created: https://drive.google.com/file/d/1XyqKO6i5WqqzaxhnneIeteR2c2pkJwq5/view?usp=sharing

@ShizuKoto  Could you try comparing the current release with this one to see which one feels better? I can definitely still feel a bit of choppiness but I can't tell if overall performance became better, worse, or the same

Thanks so much for your help so far btw! :D

**Comment by ShizuKoto** [comment]
I tried scrolling in the release for 20min straight and while it was definitely smoother overall, it actually used up a lot of memory.
After a few posts it got to a stable 5-10fps and only got stuck whenever I closed a post after opening it to read the comments.
I took pics of my phone's memory before and after.
![Screenshot_20230628_054516_Device care](https://github.com/hjiangsu/thunder/assets/134916480/4356eec8-7632-4944-91f8-5ad95e559607)
![Screenshot_20230628_060527_Device care](https://github.com/hjiangsu/thunder/assets/134916480/b07ba2fe-1a41-407c-85fe-acc122c8ec9d)

It took up 5.5GB which is quite a substantial number 😅

> Thanks so much for your help so far btw! :D
No! Thank you for the awesome app 🐱

**Comment by hjiangsu** [comment]
Hmm okay! Thanks for testing it - I'll keep looking into it to see if I can reduce that even more, there might be a memory leak which is why its using so much RAM

**Comment by hjiangsu** [comment]
@ShizuKoto  I'm back again with another test if you're up for it! This is the link to the APK: https://drive.google.com/file/d/13PMNi4CX3r1i7uNJnzpt_JIKLIDniOGy/view?usp=sharing

**Comment by ShizuKoto** [comment]
Nice! You solved the issue.
Memory usage didn't pass 470MB after browsing 20min straight.
Some choppiness was still there which I imagine is due to the app loading posts while scrolling. But in-between that post-loading-coppiness everything seems smooth and fine. (Happens when you try to scroll a bit faster past multiple posts)

Awesome! 🫡

**Comment by hjiangsu** [comment]
Oh man that great to hear! Yeah, I eventually want to remove that choppiness from loading posts but the more pressing issue has hopefully been resolved

Thanks so much for helping test

**Comment by hjiangsu** [comment]
I will mark this as "fixed in next release", but I do want to get feedback on this issue if it continues to affect a lot of users

**Comment by Fmstrat** [comment]
I have an old S9 so it has this problem a lot. Once the new release hits F-Droid I'll try it out on it.

Does Flutter have the ability to load content off-UI-thread like RN? That's how I handled it in my image viewer, basically loaded images in another thread then assigned them to the UI.

**Comment by hjiangsu** [comment]
I'm not too sure if its possible to load images in a different thread, but I think the issue has been mainly solved _crosses fingers_ and will come out in the next release

The main issue that was causing a lot of the lag to occur was that the list of posts were not being properly deallocated from the list. The list itself is supposed to only load up the posts which are immediately viewable on screen, and should remove any that are no longer visible. There was an issue where the off screen posts were not being offloaded, which meant that there was increased memory usage over time - particularly with posts with a lot of images

**Comment by grouma** [comment]
I'm using v0.2.1-alpha.3+9 on a Pixel 7 Pro. Scrolling through posts is mostly smooth with occasional stutter, especially when additional data is loaded. However scrolling through long comment threads is very choppy. It feels like it may be limited to 60 fps.

**Comment by hjiangsu** [comment]
> Scrolling through posts is mostly smooth with occasional stutter, especially when additional data is loaded

Theres definitely improvements that could be made with data loading/fetching to reduce those stutters, but that might have to come in later in the future!

> However scrolling through long comment threads is very choppy. It feels like it may be limited to 60 fps.

Yeah, I also got further confirmation that comment scrolling is stuttering. This is most likely also the same issue that was causing the post feed to stutter, so I'll have to look into how to handle that situation for the comment view. It's most likely not deallocating resources properly, which would make it noticeable for longer comment threads as opposed to shorter ones

**Comment by hjiangsu** [comment]
> Yeah, I also got further confirmation that comment scrolling is stuttering. This is most likely also the same issue that was causing the post feed to stutter, so I'll have to look into how to handle that situation for the comment view.

I'm working on some fixes to this issue, and it should be ready for the next nightly release (either later today or tomorrow depending on time)

**Comment by hjiangsu** [comment]
I have just released a pre-release version v0.2.1-alpha.1+11 with changes to hopefully improve performance within long comment threads - test it out if you are able to and let me know the results!

**Comment by hjiangsu** [comment]
Closing as its been released in v0.2.1+11!
