### ISSUE TITLE
Edge-to-edge images mode cuts top and bottom of the image bya few pixel

### ISSUE THREAD

**Issue by tunglith** [hjiangsu/thunder#247]
This one is pretty self-explanatory, the setting cuts off the top and bottom of the images making it hard to read some texts, disabling the setting shows the image in full height.

**Comment by Fmstrat** [comment]
This is unrelated to the webp issue, and has been fixed and merged in https://github.com/hjiangsu/thunder/pull/267

**Comment by hjiangsu** [comment]
I'll close this issue as it's marked as fixed
