### ISSUE TITLE
Display banners

### ISSUE THREAD

**Issue by CTalvio** [hjiangsu/thunder#258]
Both users and communities can have banners. I propose something like this:

![Screenshot_20230706_032048](https://github.com/hjiangsu/thunder/assets/4365015/02afa004-3446-45c0-9806-d4cefeb7111a)

This is already in-app, though I have not found a good way to fallback to no banner for users and communities that do not have one. It seems BoxDecoration is unable to fall back to a color the way CircleAvatar can.

@hjiangsu You can assign this one to me.

**Comment by hjiangsu** [comment]
I like the look of it, it keeps it clean. I would say that if a community has no banner, then default it to what it is currently (match the background colour)

If you provide the code for the BoxDecoration, I can suggest ways to fallback to no banner if you'd like

**Comment by CTalvio** [comment]
Fallback to solid color is the plan.

As far as I could tell, BoxDecoration with an image can only fallback to another image, by using a conditional similar to the one currently in CircleAvatar.

The simplest solution would be to just give it a blank placeholder image.

But the perfectionist in me wonders if there is a better solution. I tried to look up ways to conditionally disable the whole BoxDecoration, but didn't find anything.

I can get you the code later.

**Comment by hjiangsu** [comment]
I can give you a quick alternative - you can probably set a conditional on checking if the image exists first and then setting the box decoration

It would be something like this:

```dart
return Container(
  decoration: communityInfo?.communityView.community.banner != null ? BoxDecoration(...) : null,
  child: Container(...)
```

I _think_ that `decoration` can be set to null to trigger the default behaviour but maybe double check that!

**Comment by CTalvio** [comment]
@hjiangsu That works perfectly. Exactly what I wanted to do. PR incoming after some fiddling.

**Comment by CTalvio** [comment]
@hjiangsu you can mark this ready in the next release?

**Comment by hjiangsu** [comment]
Done!

**Comment by machinaeZER0** [comment]
I think this looks super clean! My only thought (and I know this was coded using the current layout as a base, with the icon next to the title/community info) is that this layout hides a lot of the community's banner, which seems less than ideal depending on what's being displayed.

I unfortunately don't have a screenshot of it handy, but I really liked the way Boost did this on reddit - I believe they had the banner mostly visible, with the community icon centered and slightly offset below? I've tried to create a rough mockup of what I mean:

![icon + banner mockup](https://github.com/hjiangsu/thunder/assets/3624023/7ff30e9f-e598-40cc-9fbb-dd3b0a5568c4)

@hjiangsu Thoughts on pursuing this sort of layout at a future date? I could play around with the mockup more if more work needs to go into where to put the additional icons/info I left out. Obviously takes up more screen real estate, but being able to see more of the banners feels like it would be a win!

**Comment by CTalvio** [comment]
The current webUI also hides a lot of the left side of the banner:

![Screenshot_20230709-075247384.jpg](https://github.com/hjiangsu/thunder/assets/4365015/927d2434-b62c-4eab-942a-5b516745c6d6)

I wanted something that followed an analogous layout, as good community admins will pick icons that go well together, and specifically do so in this overlapping left side arrangement.

One thing I'm already considering, is shifting how the banner is displayed to the right at bit so as to bring out that 25% that is behind the part of the gradient that has no transparency at all.

I also initially considered the more fully visible banner, but once I tested the gradient idea, I felt it fit with Thunders more muted design very well.

**Comment by machinaeZER0** [comment]
That all makes sense to me! Still on the fence a little about the gradient (even though it does look classy), but I think you're totally right that since the web client is laid out with the icon on the left, matching that layout is a good call :)

**Comment by CTalvio** [comment]
![Screenshot_20230709-174004634](https://github.com/hjiangsu/thunder/assets/4365015/d8edb524-56e8-46b0-b5b8-cd8616bc2a75)

The banner looks a lot better now IMO with the black post separators in the latest alpha, rather than the grey ones.

**Comment by hjiangsu** [comment]
I'll close this issue since its been released, but feel free to continue discussion if needed!
