### ISSUE TITLE
Can't add second account 

### ISSUE THREAD

**Issue by bikasv** [hjiangsu/thunder#278]
**Description**  
Right now whenever I try adding a second account, I met eith database error and account doesn't get added. I tried accounts from various instances, but result is the same.

**How to Reproduce**  
1. Go to account tab
2. Click on add account 
3. Enter details 
4. See error that account can't be added and app asks you to refresh page

**Expected Behavior**  
A new account should be added and there should be easy way to make one active.

**Screenshots**  
![Screenshot_20230708_100507](https://github.com/hjiangsu/thunder/assets/1210099/4aaef226-96e9-4562-82bc-e888c9e317eb)

**Device & App Version:**  
 - Device: Samsung S21 Ultra
 - OS: Android 13 (One UI 5.1)
 - Version 0.2.1-alpha.2

**Comment by hjiangsu** [comment]
Did you try to clear your app data, and reinstall the app? There was a slight change to the local database which might've caused that issue

**Comment by hjiangsu** [comment]
Could you try the latest pre-release (nightly) version and see if you can add a second account? This is the link to the pre-release: https://github.com/hjiangsu/thunder/releases/tag/v0.2.1-alpha.5%2B11

**Comment by bikasv** [comment]
It's working now. I had to uninstall the previous version fully and install the latest version. But it fixes the issue now.

**Comment by hjiangsu** [comment]
Awesome, I'll close this issue if thats the case!
