### ISSUE TITLE
Comments preview not working, showing only grey screen

### ISSUE THREAD

**Issue by wadamT** [hjiangsu/thunder#279]
**Description**  
The preview that show markdown formatted comments does not working, showing only grey screen. Comments do not need to be in markdown formatted, just plain comments also affected.

**How to Reproduce**  
1. Go and comment under a post
2. Click Preview
3. See error

**Expected Behavior**  
Formatted comments

**Screenshots**  
![Screenshot_20230708-154549](https://github.com/hjiangsu/thunder/assets/70312852/8e7d5fdf-066f-4e08-8038-96a4bbd368fe)
![Screenshot_20230708-154557](https://github.com/hjiangsu/thunder/assets/70312852/cd938ef9-2036-4f92-ac8d-4c670b3143d2)

**Device & App Version:**  
 - OS: Android 9
 - App Version: v0.2.1-alpha.2+11

**Additional Context**  
This bug also affects the preview of creating new posts.

**Comment by hjiangsu** [comment]
This is known and fixed in an upcoming release!

**Comment by hjiangsu** [comment]
I have released a pre-release (nightly) version which should fix this issue if you would like to take a quick look: https://github.com/hjiangsu/thunder/releases/tag/v0.2.1-alpha.5%2B11

**Comment by wadamT** [comment]
Can confirm. This bug is fixed in v0.2.1-alpha.5+11.
