### ISSUE TITLE
add an "About" page in settings

### ISSUE THREAD

**Issue by shortwavesurfer2009** [hjiangsu/thunder#29]
**Is your feature request related to a problem? Please describe.**
No

You should add an "About" section linking people to the github repo and your other social accoints so we can mention you when we pist about how nice your app is

**Comment by hjiangsu** [comment]
Good idea - I'll keep that in mind for the next release!

**Comment by realeatham** [comment]
Also you should add a button to open the Lemmy community there

**Comment by hjiangsu** [comment]
Added in the latest release v0.2.1+6. Open up a new issue for any additional content that should be provided on the about page!
