### ISSUE TITLE
Setting reset on application restart

### ISSUE THREAD

**Issue by MidNightCola** [hjiangsu/thunder#31]
**Description**  
if I set the dark theme off for example, it stays like that untill I re open the app, the setting toggle is still off, but it's on dark theme, view full height image is the same as well.

**How to Reproduce**  

Set a setting different than the default
Close the app
And open it again,

**Screenshots**  
![Screenshot_20230620-220418_thunder](https://github.com/hjiangsu/thunder/assets/77248142/5cb397d7-8637-4258-b52d-708488331d7a)

**Device & App Version:**  
 - Device: Poco x3 pro
 - OS: android 12
 - Version 0.2

Thanks for the great app btw.

**Comment by hjiangsu** [comment]
Noted! I found the issue and the fix will come in the next release!

**Comment by hjiangsu** [comment]
This should be fixed in the latest release: v0.2.1+5! I will close this issue but let me know if there are still issues with this
