### ISSUE TITLE
show what instance remote communities are from

### ISSUE THREAD

**Issue by realeatham** [hjiangsu/thunder#32]
**Is your feature request related to a problem? Please describe.**
You can't tell what instance communities are from

**Describe the solution you'd like**
If a community is not local to your instance, it should show what instance it's from e.g. thunder_app@lemmy.world instead of just thunder_app when not browsing from lemmy.world.

**Comment by hjiangsu** [comment]
hmm, I would like your thoughts on where the instances should be added!

Would this be when you open up a specific community feed? or would it also apply to the individual posts?

**Comment by realeatham** [comment]
Everywhere. There are tons of communities with the same name and it can get confusing. Maybe there should be a setting to customize this tho for people that like it differently.

**Comment by hjiangsu** [comment]
Alright, I'll consider that! Thanks

**Comment by hjiangsu** [comment]
This has been added in the latest release v0.2.1+5! Let me know how it is and if there should be other places where we display the instance. For now, theres no option to change it in the settings, but that may be something to consider in the future.

I'll close this issue for now
