### ISSUE TITLE
Refreshing the feed resets sort mode to 'hot'.

### ISSUE THREAD

**Issue by jordan1776** [hjiangsu/thunder#34]
**Describe the bug**
Refreshing the feed resets sort mode to 'hot'.

**To Reproduce**
1. Go feed view
2. Change sort to anything that is not 'hot'
3. Refresh feed

**Expected behavior**
Sort mode should stay the same upon refresh.

**Smartphone (please complete the following information):**
 - Device: Xperia 1 II
 - OS: Android 11

**Comment by hjiangsu** [comment]
Yup, noted - I also saw this when I was doing some testing prior to v0.2.0-alpha, but decided to leave it be for the time being.

In an upcoming release, I'm planning to add the option to choose the default sort/feed types within the settings, so I'll revisit this issue when I work on that!

**Comment by hjiangsu** [comment]
This has been fixed by @JulianPaulus and will be released in the next version
