### ISSUE TITLE
GIF displaying

### ISSUE THREAD

**Issue by MrAntonS** [hjiangsu/thunder#39]
I guess I'll start working on GIF implementation. Haven't used Dart a lot, but it seems pretty straight forward... Hopefully

**Comment by hjiangsu** [comment]
That would be great! I _think_ gifs may already be supported, but I may be wrong

For some context - most of the media (images) currently use [cached_network_image](https://pub.dev/packages/cached_network_image) package. There are some places still that probably use `Image.network()` native function

I'll assign you to this issue, thanks!

**Comment by MrAntonS** [comment]
Yeah, I'm currently trying to figure out why it doesn't preview GIF, if you tap on them they work fine, so I'm troubleshooting if cached images support gif

**Comment by MrAntonS** [comment]
Apperantly it got fixed by a new update. :😀

**Comment by hjiangsu** [comment]
Well then, that was an inadvertent fix 😅
