### ISSUE TITLE
Full height images setting doesnt save 

### ISSUE THREAD

**Issue by ContentSpy** [hjiangsu/thunder#42]
**Description**  
Enabling full height images doesn't save if you close the app and reopen it it shows up as if it isn't turned on even though it is in the settings page 

**How to Reproduce**  
1. Enable show full height images
2. Close the app
3. Reopen it 
4. Now the images are back to how they were before and in the settings the option is still ticked somehow 

**Expected Behavior**  
It shouldn't reset if I close the app

**Device & App Version:**  
 - Device: [Samsung s20 ultra]
 - OS: [Android 13]
 - Version [0.2.0 alpha]

**Comment by hjiangsu** [comment]
This should be fixed in the latest release: v0.2.1+5! I will close this issue but let me know if there are still issues with this
