### ISSUE TITLE
Ability to view my own posts in my profile section of the app

### ISSUE THREAD

**Issue by Terkyz** [hjiangsu/thunder#47]
**Is your feature request related to a problem? Please describe.**
No. But aside from the fact that there is currently no way to access individual profiles within Thunder, I think being able to scroll through my profile from that menu would be very useful.

**Describe the solution you'd like**
That the "My profile" screen stays the same, but when I scroll I can see the history of my posts.

**Describe alternatives you've considered**
I don't think any? I cannot currently in any way achieve this at the moment in Thunder.

**Additional context**
I honestly don't know how the comments would be implemented with this function, I mean, that in an ascending order chronologically appear my newest posts to the oldest, but I don't know if it would be good if that would include the comments or how that would be.

**Comment by hjiangsu** [comment]
This will be added in the upcoming release!

**Comment by hjiangsu** [comment]
Closing as this should be fixed in v0.2.1+10!
