### ISSUE TITLE
Implementing inbox capabilities into the app

### ISSUE THREAD

**Issue by hjiangsu** [hjiangsu/thunder#48]
**Is your feature request related to a problem? Please describe.**
Inbox features are not currently implemented in Thunder. This feature is useful in order to receive various notifications (such as replies, mentions, and messages)

**Describe the solution you'd like**
The idea right now is to introduce a new bottom navigation option which will keep inbox related features in one place. The idea is to hopefully mimic how Lemmy does it at the moment, and then adjust it based on community feedback

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hjiangsu** [comment]
Closing this as this has been introduced at a basic level

**Comment by Terkyz** [comment]
Is it possible to add an icon like [this](https://i.imgur.com/xr9ouHG.jpg) (like a typical message icon in an app saying it has x number of messages, I didn't find that exact icon so I put this one) that indicates the number of notifications received in Inbox without checking?
