### ISSUE TITLE
Super zoomed in image on post

### ISSUE THREAD

**Issue by njosey** [hjiangsu/thunder#49]
On this post https://lemmy.world/pictrs/image/be388459-7c80-4799-a696-87e6825fd603.webp and probably other posts that have images posted in that way are super zoomed in when opening the image on the app and there is no way to zoom out as I have attempted that

**How to Reproduce**  
1. Go to the post linked in this issue report in the thunder app
2. Click on the image link on the post
3. Image opens up super zoomed in
4. Attempt to zoom out and won't be able too

I expected to be able to zoom out of the image to have it be sized properly 

**Screenshots**  

![Screenshot_20230623-214318](https://github.com/hjiangsu/thunder/assets/17174184/9da94ac3-307b-482d-8a9e-53d97dcfa391)

![Screenshot_20230623-214405](https://github.com/hjiangsu/thunder/assets/17174184/f60557dc-5c84-4e8a-98ad-af46e1abbd4f)
![Screenshot_20230623-214359](https://github.com/hjiangsu/thunder/assets/17174184/94ca4b50-5ea6-48c2-a994-7beb8ec410bf)
![Screenshot_20230623-214350](https://github.com/hjiangsu/thunder/assets/17174184/08dcaaee-4f6e-4774-862c-5e444ac26f80)
![Screenshot_20230623-214332](https://github.com/hjiangsu/thunder/assets/17174184/386af671-ddef-43c4-ac06-209cc7ce32cf)
![Screenshot_20230623-214329](https://github.com/hjiangsu/thunder/assets/17174184/7e153984-e8d3-4cab-a734-7d46745ddcf7)

**Device & App Version:**  
 - Device: Samsung Galaxy A70
 - OS: Android 11
 - Version: Thunder v0.2.1+5

**Additional Context**

**Comment by hjiangsu** [comment]
Hmm, I cant recreate the issue. Do you have a bit more specifics?
- Did you open the image from the feed? Or did you open the image once you tapped into the post?
- Does this happen with any other image?

This is what I see (iPhone 13 Pro)

![image](https://github.com/hjiangsu/thunder/assets/30667958/db70ef2d-7b88-4dff-87e6-44cc4ed592f6)

![image](https://github.com/hjiangsu/thunder/assets/30667958/3e13c98a-2110-47ba-b3bd-ff937ad3f8e4)

**Comment by njosey** [comment]
Weird because I see the image as a link instead

![Screenshot_20230624-144751](https://github.com/hjiangsu/thunder/assets/17174184/6c74de16-c8a7-405a-8186-ea84c2383027)

When I tap on the link to open the image it opens it up in that super zoomed in view that I cant zoom out of

**Comment by njosey** [comment]
https://github.com/hjiangsu/thunder/assets/17174184/ea753b0b-5308-4c60-b685-128700d3b749

I have attached a screen recording of the issue to help show it better

**Comment by hjiangsu** [comment]
Oh, interesting - it seems like the picture was not recognized properly, and instead a link was created. I'm guessing that when you tapped on the link, it actually opened it up in the in-app browser which is why you cant zoom in or out of it

I'll have to see if I can recreate that issue with the picture not being recognized properly. What instance are you logged into?

**Comment by njosey** [comment]
Im logged into the lemmy.world instance

**Comment by hjiangsu** [comment]
I'm wondering it this issue has been fixed in the latest release v0.2.1+7, as it should bring up a better in-app browser which should allow for zooming in/out?

**Comment by njosey** [comment]
I'll download it to test out in my free time

**Comment by njosey** [comment]
I've tested it and the issue is fixed because of the new in app browser

Doesn't open super zoomed in and I can freely zoom in and out
