### ISSUE TITLE
Support iOS 15

### ISSUE THREAD

**Issue by dtantono** [hjiangsu/thunder#5]
Hi
I know there is iOS client out there for Lemmy. But, it only support iOS 16 and later. But, I hope this app will support iOS 15 and BTW, it is still relevant worldwide. What do you think?

**Additional context**
https://gs.statcounter.com/ios-version-market-share/

**Comment by hjiangsu** [comment]
Since this app is built with Flutter, it makes it a bit easier to target lower iOS versions. However, keep in mind that this could change if there are features in the future which require specific features from a higher iOS version.

Currently, the app should support iOS version 11.0 and up!

<img width="665" alt="image" src="https://github.com/hjiangsu/thunder/assets/30667958/20c0a8ae-2ea0-4a63-885f-f88627cec5a0">

**Comment by tristan-k** [comment]
@dtantono Off-topic: Why dont you use Testflight for Beta-Testing? There a lot of people who would probably like to test the app but don't know how to use AltStore,

**Comment by dtantono** [comment]
There is no test flight link atm

**Comment by hjiangsu** [comment]
> @dtantono Off-topic: Why dont you use Testflight for Beta-Testing? There might be a lot of people who would like to test the app but don't know how to use AltStore.

Hey! Theres a few main reasons for not using TestFlight or Google Play (and derivatives from that) at the current moment.

- Before deploying the app to those services, I would like to be able to add in some more core functionalities that are currently missing (creating posts, replying to comments, comment actions for upvote/downvote/save, multiple accounts/instances, etc)
- Unfortunately, setting those services up will require some overhead (and learning 😅) on my end, and as this is still a side project which I work on during my spare time outside of my current work/life, it would mean less time for me to work on the core missing features!
- Opening the app out to a larger audience brings the expectation of faster updates which I may or may not be able to accomplish yet, but hopefully will as more people help contribute to the project

All that being said, I'm still definitely open to the idea of bringing the app to those services eventually (and when I have the capacity to do so)!

**Comment by hjiangsu** [comment]
Closing this as the app should already be supporting iOS 15
