### ISSUE TITLE
Sharing a Post or Comment

### ISSUE THREAD

**Issue by UniqueActive** [hjiangsu/thunder#55]
Whenever I see a nice post that I want to show to my wife or a friend, I remember that there is no apparent way to share a post or comment yet. 😅

Perhaps long-pressing a post or comment should provide an option to share the link, which also includes copying the link since at least the Android sharing menu allows copying to clipboard.

It could also be a swipe functionality but that will probably make the swipe too crowded, so I'd prefer a button or long-press. Perhaps a dedicated button for posts and long-press for comments? Let me know what you think. :)

A separate but related feature would be just sharing/copying an image link, I also propose long-tap for this since a post or comment can contain many images.

**Comment by hjiangsu** [comment]
Some initial sharing issues have been added in the latest release v0.2.1+6! However, I would like to improve that experience even more, so please provide some feedback on the latest release when you can :D 

For links, you can share them when you tap on the link (it opens up the preview, and you have the option to share that link)
For posts, there is a new sharing icon when you open the post which will open up the system share dialog

**Comment by UniqueActive** [comment]
Thanks for the speedy improvement, I am very happy with how you implemented post sharing and the additional options when opening links! Now the only remaining part of this issue is sharing a comment, do you have ideas how to best do this?

**Comment by hjiangsu** [comment]
Hmm, there may be a way to create a permalink to a specific comment, but I would have to take a look into that further

**Comment by UniqueActive** [comment]
Here is an example for a comment permalink as Jerboa generates it: https://lemmy.world/comment/579069

**Comment by hjiangsu** [comment]
I'll take that into consideration for implementing the comment permalinks! Thanks

**Comment by hjiangsu** [comment]
I'll close this issue for now, and moving the comment permalink/sharing to #232
