### ISSUE TITLE
mark posts as read

### ISSUE THREAD

**Issue by shortwavesurfer2009** [hjiangsu/thunder#58]
**Is your feature request related to a problem? Please describe.**
When a post is tapped and then you return to the main feed the post is still the same color so you cannot tell it has been opened

**Describe the solution you'd like**
The post title should take on a darker color in dark mode once it has been opened to show the user it has been read

**Comment by hjiangsu** [comment]
Yup, marking posts and comments as read has not been implemented yet - I would like to address this sometime soon though!

**Comment by tunglith** [comment]
Adding to that functionality :
- A mark post as read when scrolled over setting
- A remove read posts button to get to fresh content more easily (Relay for Reddit type)

**Comment by hjiangsu** [comment]
@tunglith could I get you to make those two points into separate issues? They're large enough and scoped enough to be able to work on the independently

Thanks! I'll close this issue since the original issue has been resolved
