### ISSUE TITLE
Default search sort order doesn't seem relevant

### ISSUE THREAD

**Issue by Benjamint22** [hjiangsu/thunder#63]
**Description**  
The default sort order in the "Search" tab doesn't seem to give particularly relevant results for some reason.

I tested changing the sort order in `search_bloc.dart` from default to `SortType.Active`, and it looks like the results are much more relevant (subjectively).

I'm not sure what's the default sort order. It looks like it may be "Hot" since it gives me the most similar results. I'm not sure what the most relevant sort order is, but I think "Active" or "Top[somerange]" looks best.

I can open a PR if you want.

**How to Reproduce**  
1. Go to the search page.
2. Search "technology"

**Expected Behavior**  
I expected the most popular (or active) communities to be near the top results, but have to scroll far to find them.

**Screenshots**  

<table>
<tr>
 <th width="33%">Default (current)
 <th width="33%">`SortType.Active`
 <th width="33%">`SortType.TopAll`
<tr>
 <td>

![image](https://github.com/hjiangsu/thunder/assets/6548393/cebe2aa2-79a3-4ed8-a3a8-edb2a795fb91)
 <td>

![image](https://github.com/hjiangsu/thunder/assets/6548393/d8d6643d-323a-4d21-b7e5-3f2cc0fe1cea)

 <td>

![image](https://github.com/hjiangsu/thunder/assets/6548393/72261836-c3f0-434d-8049-356076a21c55)
</table>

**Device & App Version:**  
 - Device: ROG Zephyrus G14 GA401QM_GA401QM
 - OS: Microsoft Windows 11 Home 10.0.22621 Build 22621
 - Version: [v0.2.1-prerelease+5](https://github.com/hjiangsu/thunder/releases/tag/v0.2.1-prerelease%2B5)

**Additional Context**  
I am on the `lemmy.world` instance and I'm authenticated.

**Comment by Benjamint22** [comment]
This is subjective, no hard feelings if you disagree :stuck_out_tongue_winking_eye:

**Comment by hjiangsu** [comment]
I agree - we should probably make the default either active or top. I'm not too sure what the default is either, but I'll leave it to your discretion!

In the future, it would be best to add in a way to change between sort types within the search as well

**Comment by Benjamint22** [comment]
> I agree - we should probably make the default either active or top. I'm not too sure what the default is either, but I'll leave it to your discretion on the default it should be!

Awesome! Will open a PR.

> In the future, it would be best to add in a way to change between sort types within the search as well

Fully agreed!

I'm tempted to work on that after.

**Comment by hjiangsu** [comment]
That would be awesome, thanks! :D
