### ISSUE TITLE
Can't download update from Update-New-Version-webview

### ISSUE THREAD

**Issue by krestenlaust** [hjiangsu/thunder#68]
**Description**  
There was a banner saying there is a new version available. It links to the page releases page. The problem is I can't click links in the view.

**How to Reproduce**  
1. Press update banner. Entering webview
2. Try to click download link.

**Expected Behavior**  
Probably redirects to browser and starts download.

A solution could also be to just open the browser right away.

**Screenshots**  
n/a

**Device & App Version:**  
 - Device: OnePlus 6T
 - OS: OxygenOS 11.1.2.2
 - Version v0.2.1+5

**Additional Context**  
Long pressing on the link didn't do anything either.

**Comment by hjiangsu** [comment]
Hmm, hopefully this is fixed as the new release allows you to open up links in the external browser. Let me know your thoughts!

**Comment by krestenlaust** [comment]
Is it the most recent update or the previous one? If it's the latter, then I could just install that one and try it out :)

**Comment by hjiangsu** [comment]
If you install v0.2.1+6, you should receive a notification for 0.2.1+7, where you have the option to the link in an external browser!

If you want to test that out, that would be great

**Comment by krestenlaust** [comment]
So, I can open the github page as before, the link still doesn't work in the current browser, but I can just open it in the external one with the new button, so it shouldn't be an issue anymore.

It is a little weird though. It is as if there's two layers of internal browsers, because it still doesn't open open the real browser app.

Visual explanation:
App - click link -> Internal browser that doesn't support links - press open external -> Some kind of embedded chrome browser that supports links - Burger menu press open in chrome -> real browser.

I have the github app installed, and the second browser is listed as an app inside that one, this might be related 🤔

**Comment by krestenlaust** [comment]
I just tested it with another link and the extra browser is just inside Github App, so there's no issue anyway :)
