### ISSUE TITLE
Initial read/not read toggle in the inbox is reversed

### ISSUE THREAD

**Issue by tunglith** [hjiangsu/thunder#69]
**Description**  
Upon openning the inbox, not read replies appear activating the toggle enveloppe in the top right refreshes the page but the same messages appear. Clicking the toggle another time shows the read replies properly :

- Unread by default
- Tap the enveloppe and toggles unread so no changes
- Tap the envelopp and toggle read and now the old replies appear

**How to Reproduce**  
1. Go to the inbox
2. click the enveloppe toggle and notice no changes
3. Click the toggle again and notice the changes

**Expected Behavior**  
Clicking the toggle the first time should change the page from "not read" to "read".

**Screenshots**  

**Device & App Version:**  
 - App version v0.2.1+6

**Comment by hjiangsu** [comment]
Just an update on this - this should be fixed in the next release

**Comment by hjiangsu** [comment]
Closing issue - fixed in release v0.2.1+8!
