### ISSUE TITLE
Network permission missing

### ISSUE THREAD

**Issue by Max-Q** [hjiangsu/thunder#7]
**Describe the bug*
No content loaded after app startup
When trying to login: Socket exception failed host lookup

**To Reproduce**
Install under GrapheneOS
Launch Software
Check App permissions

**Expected behavior**
App needs to request Network permission. So it can access network/ internet

**Smartphone (please complete the following information):**
 - Device: GrapheneOS on Pixel

**Comment by hjiangsu** [comment]
What version are you running? The internet permissions issue should be fixed in v0.1.1-alpha! See: https://github.com/hjiangsu/thunder/issues/2

**Comment by Max-Q** [comment]
My bad, had the version 0.1 from Izzy. With the last version from. Github it works.
