### ISSUE TITLE
another unlabeled button

### ISSUE THREAD

**Issue by shortwavesurfer2009** [hjiangsu/thunder#70]
**Description**  
The reply button at the bottom of a post appears to be unlabeled. See screenshot below

**How to Reproduce**  
1. Go to settings > accessibility > talkback and turn it on
2. Open a post in thunder
3. Touch the reply button highlighted in the screenshot

**Expected Behavior**  
![Screenshot_20230625-055922_thunder](https://github.com/hjiangsu/thunder/assets/116814522/364aa444-d8c2-410e-a36e-343a01cd3b13)

**Screenshots**  

**Device & App Version:**  
 - Device: [e.g. iPhone6] Motorola One 5G Ace
 - OS: [e.g. iOS8.1] Android 11
 - Version [e.g. 22] 0.2.1+7

**Additional Context**

**Comment by hjiangsu** [comment]
This should be fixed in the next version!

**Comment by hjiangsu** [comment]
Closing issue - fixed in release v0.2.1+8!
