### ISSUE TITLE
Custom "accent color" in theme?

### ISSUE THREAD

**Issue by machinaeZER0** [hjiangsu/thunder#76]
Currently the "accent color" for Thunder is some shade of purple, depending on whether you're in light or dark mode. I'd imagine this would be incredibly low priority, but in the future it would be cool to be able to choose from a selection of colors, edit with some sort of color picker tool, or (in the case of Android, at least) be able to inherit the accent color set by your OS!

**Comment by machinaeZER0** [comment]
Heck yes!! Pumped for the next release :D Thank you!

**Comment by machinaeZER0** [comment]
Noting here that this is included in the latest release! The only thing I might consider adding support for would be the color of the floating New Post button, which looks to be hard-coded still. That might be personal preference, though!

**Comment by machinaeZER0** [comment]
@hjiangsu - feel silly for not catching that the FAB actually is getting themed when I toggle the Material You setting! My accent color themes stuff to be a light blue, but the FAB changes to be a darker blue button with a light blue symbol.

I'm wondering if it would be possible to invert this so the button itself is always the accent color (which I believe would generally make the button a lighter color, and the button's icon a darker color)? I think that would theoretically make the FAB look more uniformly themed when Material You is toggled, but that might just be personal preference!

![Screenshot_20230629-234253](https://github.com/hjiangsu/thunder/assets/3624023/e7c8d8fa-65d5-485e-9288-17a5be52f5ba)

Can also make this a separate ticket if that makes more sense!

**Comment by hjiangsu** [comment]
@machinaeZER0 I would say to make that into a separate issue so that it's easier for me to keep track of!

I'll close this issue since it somewhat resolves the original issue :D
