### ISSUE TITLE
[Compact Mode] Option for thumbnails on the right side

### ISSUE THREAD

**Issue by machinaeZER0** [hjiangsu/thunder#78]
Hopefully self explanatory - absolutely a personal preference thing, and no idea how the rest of the community feels about it, but if it's possible to implement in the future that would be super!

**Comment by hjiangsu** [comment]
This is done, and will be released in the next version! Sneak preview:

![simulator_screenshot_CA9CAD6F-195B-4F15-B65F-47E2AB03EA9F](https://github.com/hjiangsu/thunder/assets/30667958/efd8d76a-5536-42b0-85aa-b8e6810eb52b)
![simulator_screenshot_4487EC9C-E5C8-4D6A-A172-6E79CD745CA1](https://github.com/hjiangsu/thunder/assets/30667958/aa3c71c5-a126-4dfc-b285-608cedfdd740)

**Comment by machinaeZER0** [comment]
Ahhhhhhh it's perfect!! Thanks so much for looking into this, @hjiangsu!

**Comment by hjiangsu** [comment]
Closing issue - fixed in release v0.2.1+8!
