### ISSUE TITLE
Autofill for Login does not work on Android

### ISSUE THREAD

**Issue by SZenglein** [hjiangsu/thunder#8]
When adding an account, I would expect my password manager to fill in my credentials, but no popup whatsoever is triggered by the input fields.

1. Go to account
2. Log out
3. Click the username field
4. nothing happens

**Expected behavior**
When tapping the username or password field to write, the Android autofill service should pop up.

 - OS: Android 13
 - App Version: 0.1.1-alpha

**Comment by hjiangsu** [comment]
Looking at it briefly, it seems like it should be fairly easy to handle support for inputs with the device's password manager. I'll take this into consideration!

**Comment by hjiangsu** [comment]
Update on this - this feature should be introduced in the next release! It has currently been tested on iOS, but should hopefully work with Android as well

**Comment by hjiangsu** [comment]
This feature should now be released in version v0.2.0-alpha. I'll close this issue, but it would be great if you could provide feedback on it as it has not yet been tested on an physical Android device!

**Comment by SZenglein** [comment]
@hjiangsu I can confirm it works.
