### ISSUE TITLE
[Updated] Long-press posts for popup menu options

### ISSUE THREAD

**Issue by machinaeZER0** [hjiangsu/thunder#81]
One of my all-time favorite features of Boost for Reddit (and the main reason it became my go-to Reddit app) was the ability to quickly hide unwanted communities from my feeds. Boost accomplishes this through a popup menu when you long-press a subreddit's name on a given post (screenshot attached)
![Screenshot_20230622-064017](https://github.com/hjiangsu/thunder/assets/3624023/f41fbee1-8f3e-4f6c-8e32-c63fb97eb8a0)

If this were implemented in Thunder I believe it would be the only Lemmy app with the ability to hide communities without needing to click through/navigate to said community, so I'd love to see it appear someday if it feels useful and impactful!

Side note - long-press menus in general are so rad, hahah. The one above also gives quick access to learn more about a subreddit, which is another thing that could potentially be cool to see in the future from Thunder (but is probably out of scope for this specific ticket)

**Comment by MaienM** [comment]
Jerboa has this, though the menu is opened with ... instead of long press. 

![Screenshot_20230625-190933_Jerboa for Lemmy](https://github.com/hjiangsu/thunder/assets/583129/16a12ef9-162a-4c39-95c2-63e69bb0e501)

**Comment by machinaeZER0** [comment]
Oh shoot! I had no idea - I use Jerboa's list view which doesn't have the [...] element! I guess it would change this ticket, but being able to long press anywhere on a post to get a menu like the above would be amazing

**Comment by hjiangsu** [comment]
I can take both of those into consideration - thanks for creating the issue!

**Comment by krestenlaust** [comment]
@machinaeZER0 can you check whether this has been added in the latest update? I think so, but I'm not sure if it has all the features planned in this thread.

**Comment by machinaeZER0** [comment]
I think this is now broadly added - issue #183 nods to the block functionality I was hoping for in this popup menu, so I'd consider closing this and pursuing there, or closing that one and continuing feature development here!

**Comment by krestenlaust** [comment]
I believe joining the discussion over there and closing this one, is the right choice. As this issue "Long-press posts for popup menu options" is (for the most part) solved now :D

**Comment by machinaeZER0** [comment]
Sounds like a plan!
