### ISSUE TITLE
Navigation Bar on Android - Burn-in

### ISSUE THREAD

**Issue by TigerCraneStyle** [hjiangsu/thunder#83]
The navigation bar is pure black. Can it be changed to use the app color or Material You coloring like most Android apps.

The navigation bar is one of the areas of the screen that's at most risk for burn-in as it's static. Android has remedied this by giving app devs the ability to change the color.

Granted, burn-in happens over long periods of time, but this app is so smooth that I plan on using it for the long haul.

![Screenshot_20230625-120657](https://github.com/hjiangsu/thunder/assets/131628729/2e856682-6ced-4f7f-b0e5-1594a8770034)

**Comment by machinaeZER0** [comment]
I believe it is technically possible to set up the space around the nav bar itself to show actual app content, isn't it? I think either that or it can be made to "fake it" somehow... unless the color it's changed to is dynamic in some way I think you'd be equally susceptible to burn-in (unless I'm misunderstanding), but I do think it would make sense for that area to theme itself to match the setting of the app - in your case, a black bar on a white background I think?

**Comment by TigerCraneStyle** [comment]
You're right on both counts. First being that yes, there is a way to make the navigation bar transparent to where text can be seen being it when scrolling. I temporarily reinstalled the Reddit app Sync Dev and took a screenshot that I've attached below.

![Screenshot_20230625-215129~2](https://github.com/hjiangsu/thunder/assets/131628729/db2e415e-2cfc-4e71-bfc1-2d8483c59657)

Second count... yes the navigation bar being the same color of the app would also help with burn-in. When using the dark or pure black theme in the Thunder app, the navigation bar underneath the drawer is still lighter than the navigation bar itself.  I've attached a picture of the navigation bar while using the pure black theme below.

![Screenshot_20230625-232041](https://github.com/hjiangsu/thunder/assets/131628729/28e1467e-f6ad-4850-bdcc-8532edcaaceb)

Thx for replying, MZ. I'm really digging the app.

**Comment by hjiangsu** [comment]
Yup, I think this is definitely possible, I just need to take a closer look at it!

In fact, for some reason, on iOS, it already fills the bottom gap with the colour but it doesn't do the same on Android

![simulator_screenshot_5787451A-D46C-4E41-B308-F5C2EB329CAB](https://github.com/hjiangsu/thunder/assets/30667958/03d2d65d-3deb-4302-b15e-d3a7ff661f9b)

**Comment by TigerCraneStyle** [comment]
> Yup, I think this is definitely possible, I just need to take a closer look at it!
> 
> In fact, for some reason, on iOS, it already fills the bottom gap with the colour but it doesn't do the same on Android


The layout in your screenshot is perfect. Thanks for being willing to look into it on the Android version, hjiangsu.

**Comment by machinaeZER0** [comment]
Ahh, @TigerCraneStyle you were right - I was looking at the AMOLED theme for reference, but I happened to be looking at a part of the app where the nav bar was hidden at the bottom! You're right that the color can change depending on not only the theme, but on the fly as elements are (or are not) displayed. Good catch!

**Comment by TigerCraneStyle** [comment]
> Ahh, @TigerCraneStyle you were right - I was looking at the AMOLED theme for reference, but I happened to be looking at a part of the app where the nav bar was hidden at the bottom! You're right that the color can change depending on not only the theme, but on the fly as elements are (or are not) displayed. Good catch!

Thx, MZ.

**Comment by hjiangsu** [comment]
Update on this, I think I managed to get it to work, but I dont have a physical Android device to test with. It'll be released in the next version!

For now, this is how it looks like on the android simulator:
<img width="529" alt="image" src="https://github.com/hjiangsu/thunder/assets/30667958/6c7e8f9a-bb67-4827-9b8e-8d8682303758">

**Comment by machinaeZER0** [comment]
I'll test different themes on my Pixel once the update is out! :)

**Comment by hjiangsu** [comment]
Closing issue - fixed in release v0.2.1+8!

**Comment by TigerCraneStyle** [comment]
> Closing issue - fixed in release v0.2.1+8!

Thanks again for fixing this. The layout even fills out the whole screen on the Pixel Fold! 

![Screenshot_20230627-193649](https://github.com/hjiangsu/thunder/assets/131628729/6e5a4a48-d990-4ebb-af7a-029ab193f967)

Seriously, this is the most polished Lemmy app out there. Will it eventually make it's way to the Playstore? Until then, maybe a donate option in the app?
