### ISSUE TITLE
Swipe Customizations 

### ISSUE THREAD

**Issue by Wailzy** [hjiangsu/thunder#84]
**Is your feature request related to a problem? Please describe.** 

Not exactly a problem, but a feature on another app (Apollo for iOS) that I have become long accustomed to since its release, that has become a creature comfort. For me personally in the way that I utilize the app, it makes sense for left-right swipe anywhere on the screen to take me back to the home screen/previous screen I was on if I’ve been following comment chains and links to other posts. 

**Describe the solution you'd like**

I am attaching two photos of the _gestures_ options listed in Apollo. If needed I can describe more clearly how they work. Some implementation of this beyond upvoting/downvoting comments would be appreciated. 

**Describe alternatives you've considered**

I have considered just a left-right directional swipe implementation outside of the comment area to also return to the previous screen. 

**Additional context**

![A55055D3-EAB0-4F6F-B8F4-1627AF61D696](https://github.com/hjiangsu/thunder/assets/137726328/cabcc261-6038-4978-b872-20cfc2fc9c96)
![6AD1A382-AED7-494B-843A-F788BCBCB1AE](https://github.com/hjiangsu/thunder/assets/137726328/4eb2f0ab-bd60-47e4-aa36-5077b448099c)

**Comment by hjiangsu** [comment]
This is definitely something I want to consider for the future! Allowing user-customizable gestures is something I liked from Apollo as well, so I'll see how it can be implemented in Thunder with a similar use-case

**Comment by Fmstrat** [comment]
@hjiangsu any chance in the short term we could get a left-handed toggle? I.E. just swap sides?

**Comment by hjiangsu** [comment]
I can consider adding in a quick toggle to do it!

**Comment by hjiangsu** [comment]
Just an update on this - this is currently being worked on and there should be a preview of it in the next nightly release

**Comment by Fmstrat** [comment]
@hjiangsu Is this on your short-term? Just don't want to overlap with you.

**Comment by Fmstrat** [comment]
> Just an update on this - this is currently being worked on and there should be a preview of it in the next nightly release

The timing, hah!

**Comment by hjiangsu** [comment]
Yup, I'll have something with swipe customizations in the nightly release (either tonight or tomorrow depending on time)

If you want, you can even try it out - its on the `develop` branch atm @Fmstrat

**Comment by Wailzy** [comment]
> Just an update on this - this is currently being worked on and there should be a preview of it in the next nightly release

I am so **excited** to hear this!

**Comment by hjiangsu** [comment]
A pre-release version v0.2.1-alpha.1+11 has been released with initial implementation for customizing swipe gestures. Let me know how it is and provide any feedback if possible!

**Comment by hjiangsu** [comment]
Closing as its been released in v0.2.1+11!
