### ISSUE TITLE
Image loading indicator

### ISSUE THREAD

**Issue by UniqueActive** [hjiangsu/thunder#87]
It would be great to have a little placeholder for images that are not yet loaded, just to know that they exist and are being loaded. Doesn't even need to be animated or show the progress in my opinion.

Thanks for your work! :)

**Comment by hjiangsu** [comment]
Hey just curious but is this still an issue?

**Comment by UniqueActive** [comment]
No longer an issue, now loading images have a spinning circle! Thanks for your work! :)
