### ISSUE TITLE
Setting to have thumbnails on the right

### ISSUE THREAD

**Issue by CTalvio** [hjiangsu/thunder#89]
I would like to be able to set the the post thumnails to be on the right. As I am right handed, scrolling using one hand and opening the image previews one handed would become easier.

**Comment by realeatham** [comment]
That should be a new post view mode

**Comment by machinaeZER0** [comment]
I made an issue for this earlier today, if we're both talking about compact mode! #78

**Comment by hjiangsu** [comment]
I'll close this as this is a duplicate of #78
