### ISSUE TITLE
Comments should collapse on tap anywhere

### ISSUE THREAD

**Issue by CTalvio** [hjiangsu/thunder#90]
**Is your feature request related to a problem? Please describe.**
Currently comments can only be collapsed by tapping the tiny sliver of space next to their username.

**Describe the solution you'd like**
Tapping anywhere on a comment, should collapse it.

**Comment by Benjamint22** [comment]
Alternatively, I really like the behavior of Sync for Reddit where you can collapse by holding and you can get the upvote/downvote buttons by tapping.

**Comment by machinaeZER0** [comment]
If it were combined with being able to do so anywhere on the comment, I would LOVE the option to collapse threads with a long press. For some reason long pressing to collapse feels more natural to me, not sure why. I think a single tap to collapse anywhere on a comment feels like it might get accidentally triggered more often than the current behavior, but long press + anywhere on the comment is a great combo (speaking personally)

**Comment by machinaeZER0** [comment]
That makes sense to me!

**Comment by CTalvio** [comment]
ABSOLUTELY DO NOT MAKE COLLAPSING A LONG TAP!

As an option, fine. But losing tap to collapse would be a deal-breaker for me. It would too slow. In Relay, I would often collapse over a dozen comments in quick succession, skimming their contents, browsing for threads that interest me.

A long tap would MASSIVELY slow down browsing for me. We already have gestures for votes, single tap does not need to be made into something that displays redundant UI for this.

**Comment by machinaeZER0** [comment]
Lol. Sounds like you have nothing to worry about!

**Comment by hjiangsu** [comment]
Closing issue - fixed in release v0.2.1+8!
