### ISSUE TITLE
Empty gap in feed

### ISSUE THREAD

**Issue by CTalvio** [hjiangsu/thunder#93]
**Description**  
A gap in posts in the feed.

**How to Reproduce**  
1. Go to feed
2. Scroll, sometimes you get a gap

**Expected Behavior**  
No gap

**Screenshots**  

https://github.com/hjiangsu/thunder/assets/4365015/9576a50b-0858-4d0b-b151-5025891bd7a4

**Device & App Version:**  
 - Device: Zenfone 6
 - OS: Android 11
 - Version 0.2.1+7

**Comment by CTalvio** [comment]
More info, I though to tap the gap, it is specifically this post: https://sopuli.xyz/post/908528

Being displayed as a huge empty space

**Comment by hjiangsu** [comment]
Thats weird.. that post you linked is an image, so I'm assuming what's happening here is that the image failed to load, but didn't show the corresponding "error" message

**Comment by hjiangsu** [comment]
Just an update - have you encountered this recently after that one issue?

**Comment by CTalvio** [comment]
No. It seems to have been just that one time.

**Comment by hjiangsu** [comment]
Hmm in that case I'll close this issue. If it pops up again, feel free to make a new one!
