### ISSUE TITLE
Option to default to subscribed view

### ISSUE THREAD

**Issue by petedermott** [hjiangsu/thunder#96]
**Is your feature request related to a problem? Please describe.**
I would like to be able to choose which view I see by default, currently it's the "Local posts" but as Lemmy grows I'm subscribing to more communities outside of my instance.

**Describe the solution you'd like**
Have the option to pick which view is the default, either from the settings or the user profile.

**Comment by hjiangsu** [comment]
This is done, to be released in the next version!

Contributed by @JulianPaulus in this PR https://github.com/hjiangsu/thunder/pull/80

**Comment by hjiangsu** [comment]
Closing issue - fixed in release v0.2.1+8!
