### ISSUE TITLE
Add setting to always open links in the external browser

### ISSUE THREAD

**Issue by PVCParrot** [hjiangsu/thunder#97]
**Is your feature request related to a problem? Please describe.**
When I open any external link using this app it doesn't get opened using my default browser, it instead opening using some internal browser thing. This is worse for me because I want to use Firefox with uBlock Origin at all times from the start, I also want it to part of the tabs in Firefox regardless of what app the link came from.

**Describe the solution you'd like**
Add a setting to open all external links using the def browser, not just "custom tabs" or whatever it's called by some other apps. 

**Describe alternatives you've considered**
Some apps have an option to use "custom tabs" which results in Firefox being used but it's not part of your open tabs and while ublock origin stays active you can't reach the interface for the extension unless you open it in Firefox proper which is an extra step. Some people might want this as an option but you still need to let people open using the external browser from the start. 

**Additional context**
I'm using version v0.2.1+7.

**Comment by jaimehrubiks** [comment]
Vote for this! A real web browser tab is much preferred than a webview

**Comment by hjiangsu** [comment]
Added a new setting to allow you to choose whether or not to open up links in an external browser by default! This will be released in the next version

**Comment by hjiangsu** [comment]
Closing issue - fixed in release v0.2.1+8!
